//! Generate `l10n_generated.rs` from Flutter ARB files (single source of truth).

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

use tagliacarte_core::json::{parse_str_complete, JsonContentHandler, JsonNumber};

/// ARB root is a flat map of keys to string messages; metadata keys start with `@`.
/// Push-parse only — no serde_json, no DOM.
struct ArbFlatStrings {
    depth: usize,
    pending_key: Option<String>,
    map: BTreeMap<String, String>,
}

impl JsonContentHandler for ArbFlatStrings {
    fn start_object(&mut self) {
        self.depth += 1;
        if self.depth > 1 {
            self.pending_key = None;
        }
    }

    fn end_object(&mut self) {
        self.depth = self.depth.saturating_sub(1);
    }

    fn start_array(&mut self) {
        self.depth += 1;
        if self.depth > 1 {
            self.pending_key = None;
        }
    }

    fn end_array(&mut self) {
        self.depth = self.depth.saturating_sub(1);
    }

    fn key(&mut self, key: &str) {
        if self.depth != 1 {
            return;
        }
        if key.starts_with('@') {
            self.pending_key = None;
        } else {
            self.pending_key = Some(key.to_string());
        }
    }

    fn string_value(&mut self, value: &str) {
        if self.depth == 1 {
            if let Some(k) = self.pending_key.take() {
                self.map.insert(k, value.to_string());
            }
        }
    }

    fn number_value(&mut self, _n: JsonNumber) {
        if self.depth == 1 {
            self.pending_key = None;
        }
    }

    fn boolean_value(&mut self, _v: bool) {
        if self.depth == 1 {
            self.pending_key = None;
        }
    }

    fn null_value(&mut self) {
        if self.depth == 1 {
            self.pending_key = None;
        }
    }
}

fn parse_arb_flat_strings(raw: &str) -> BTreeMap<String, String> {
    let mut h = ArbFlatStrings {
        depth: 0,
        pending_key: None,
        map: BTreeMap::new(),
    };
    parse_str_complete(raw, &mut h).expect("parse arb json");
    h.map
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let l10n_dir = manifest_dir.join("../flutter_ui/lib/src/l10n");
    println!("cargo:rerun-if-changed={}", l10n_dir.display());

    let mut locales: BTreeMap<String, BTreeMap<String, String>> = BTreeMap::new();

    for entry in fs::read_dir(&l10n_dir).expect("read l10n dir") {
        let entry = entry.expect("entry");
        let path = entry.path();
        let name = path.file_name().and_then(|s| s.to_str()).unwrap_or("");
        if !name.starts_with("app_") || !name.ends_with(".arb") {
            continue;
        }
        let code = name
            .strip_prefix("app_")
            .and_then(|s| s.strip_suffix(".arb"))
            .unwrap_or("en")
            .to_string();
        let raw = fs::read_to_string(&path).expect("read arb");
        let map = parse_arb_flat_strings(&raw);
        locales.insert(code, map);
    }

    let en = locales
        .get("en")
        .cloned()
        .expect("app_en.arb required for template keys");
    let keys: Vec<String> = en.keys().cloned().collect();

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("l10n_generated.rs");
    let mut f = fs::File::create(&out_path).expect("create l10n_generated.rs");

    writeln!(
        f,
        "// @generated by tui/build.rs from flutter_ui/lib/src/l10n/*.arb — do not edit.\n"
    )
    .unwrap();

    writeln!(
        f,
        "#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]\npub enum Locale {{"
    )
    .unwrap();
    let mut first = true;
    for code in locales.keys() {
        let variant = locale_enum_variant(code);
        let default = if first {
            first = false;
            "#[default]\n    "
        } else {
            "    "
        };
        writeln!(f, "{default}{variant}, // {code}").unwrap();
    }
    writeln!(f, "}}\n").unwrap();

    writeln!(
        f,
        "impl Locale {{\n    pub fn from_lang_tag(tag: &str) -> Self {{"
    )
    .unwrap();
    writeln!(f, "        let t = tag.split(['-', '_']).next().unwrap_or(tag).to_lowercase();")
        .unwrap();
    writeln!(f, "        match t.as_str() {{").unwrap();
    for code in locales.keys() {
        let v = locale_enum_variant(code);
        writeln!(f, "            \"{code}\" => Locale::{v},").unwrap();
    }
    writeln!(
        f,
        "            _ => Locale::En,\n        }}\n    }}\n}}\n"
    )
    .unwrap();

    writeln!(f, "static KEYS: &[&str] = &[").unwrap();
    for k in &keys {
        writeln!(f, "    {},", rust_str(k)).unwrap();
    }
    writeln!(f, "];\n").unwrap();

    for code in locales.keys() {
        let map = locales.get(code).unwrap();
        let ts = locale_table_suffix(code);
        writeln!(f, "static STR_{ts}: &[&str] = &[").unwrap();
        for k in &keys {
            let s = map.get(k).unwrap_or(&en[k]);
            writeln!(f, "    {},", rust_str(s)).unwrap();
        }
        writeln!(f, "];\n").unwrap();
    }

    writeln!(
        f,
        "/// Look up a message by ARB key (e.g. `\"compose\"`). Returns empty string if unknown.\npub fn tr(locale: Locale, key: &str) -> &'static str {{\n    let i = match KEYS.binary_search_by(|p| (*p).cmp(key)) {{\n        Ok(i) => i,\n        Err(_) => return \"\",\n    }};\n    match locale {{"
    )
    .unwrap();
    for code in locales.keys() {
        let ev = locale_enum_variant(code);
        let ts = locale_table_suffix(code);
        writeln!(f, "        Locale::{ev} => STR_{ts}[i],").unwrap();
    }
    writeln!(f, "    }}\n}}\n").unwrap();

    // Write without `writeln!(f, ...)` so `{` in the generated `format!(...)` is not parsed.
    f.write_all(
        br###"/// Replace `{name}` placeholders in a template (ARB simple case).
pub fn format_template(template: &str, pairs: &[(&str, &str)]) -> String {
    let mut s = template.to_string();
    for (k, v) in pairs {
        let needle = format!("{{{}}}", k);
        s = s.replace(&needle, v);
    }
    s
}
"###,
    )
    .unwrap();
}

/// `en` → `En` for enum variant names.
fn locale_enum_variant(code: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for c in code.chars() {
        if upper {
            out.push(c.to_ascii_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    if out.is_empty() {
        out.push('X');
    }
    out
}

/// `en` → `EN` for `static STR_EN` (SCREAMING_SNAKE_CASE).
fn locale_table_suffix(code: &str) -> String {
    code.to_ascii_uppercase()
}

fn rust_str(s: &str) -> String {
    let mut out = String::new();
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_ascii() && !c.is_control() => out.push(c),
            c => {
                use std::fmt::Write;
                let _ = write!(out, "\\u{{{:x}}}", c as u32);
            }
        }
    }
    out.push('"');
    out
}
