// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'commands.freezed.dart';

@freezed
sealed class AppCommand with _$AppCommand {
  const AppCommand._();

  const factory AppCommand.markRead({
    required String accountId,
    required String folder,
    required String messageId,
    String? requestId,
  }) = AppCommand_MarkRead;
  const factory AppCommand.refreshFolders({required String accountId}) =
      AppCommand_RefreshFolders;
  const factory AppCommand.transferMessages({
    required String sourceAccountId,
    required String sourceFolder,
    required String destAccountId,
    required String destFolder,
    required List<String> messageIds,
    required bool isMove,
    String? requestId,
  }) = AppCommand_TransferMessages;
  const factory AppCommand.sendChatMessage({
    required String accountId,
    required String folder,
    required String text,

    /// Optional HTML (Matrix rich text). Ignored for Nostr.
    String? bodyHtml,
    String? requestId,
  }) = AppCommand_SendChatMessage;

  /// Windowed message list: returns immediately; results on the session stream (§2–3).
  const factory AppCommand.listMessagesWindow({
    required String accountId,
    required String folderName,
    required BigInt startIndex,
    required BigInt limit,
    required String messageListSort,
    required String requestId,
    required bool listReady,

    /// Inclusive oldest-first rank of the first visible list row (viewport), if known.
    BigInt? visibleFirstRank,

    /// Inclusive oldest-first rank of the last visible list row (viewport), if known.
    BigInt? visibleLastRank,
  }) = AppCommand_ListMessagesWindow;
}
