// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'events.freezed.dart';

@freezed
sealed class AppEvent with _$AppEvent {
  const AppEvent._();

  /// `connectionState`: `connecting` | `connected` | `disconnected` | `error`
  const factory AppEvent.accountConnectionChanged({
    required String accountId,

    /// `email` | `nostr` | `matrix` (UI picks list vs conversation chrome).
    required String storeKind,
    required String connectionState,
    String? message,
  }) = AppEvent_AccountConnectionChanged;
  const factory AppEvent.folderListUpdated({
    required String accountId,
    required List<String> folders,
    String? hierarchyDelimiter,
    required Map<String, int> unreadByFolder,

    /// Optional UI labels keyed by folder id (e.g. Matrix room id → room / peer display name).
    required Map<String, String> folderDisplayNames,

    /// IMAP / NNTP / Matrix: **Available** tab rows (Subscribed tab is `folders`).
    List<SubscriptionAvailableRow>? subscriptionAvailable,

    /// Matrix: `m.direct` room ids for **Direct messages** tab (tab 1); tab 0 is non-DM rooms.
    List<String>? matrixDmFolderIds,
  }) = AppEvent_FolderListUpdated;

  /// One folder discovered during a refresh (§3.2 ARCHITECTURE.md). [FolderListUpdated] follows
  /// with the authoritative full list for reconcile.
  const factory AppEvent.folderFound({
    required String accountId,
    required String folderName,
    required int unread,
  }) = AppEvent_FolderFound;
  const factory AppEvent.messageFlagsChanged({
    required String accountId,
    required String folder,
    required String messageId,
    required bool isRead,
  }) = AppEvent_MessageFlagsChanged;

  /// Header for one window fetch: allocate [total] slots before row events (matches §3.2 flow).
  const factory AppEvent.messageListWindowStarted({
    required String requestId,
    required String accountId,
    required String folderName,
    required String messageListSort,
    required BigInt total,
    required BigInt startIndex,
    required String listStrategy,
    required int rowCount,
    required bool listReady,
  }) = AppEvent_MessageListWindowStarted;
  const factory AppEvent.messageListRowFound({
    required String requestId,
    required String accountId,
    required String folderName,
    required String messageListSort,
    required BigInt rank,
    required MessageListRowSummary summary,
  }) = AppEvent_MessageListRowFound;

  /// Success: `error` absent; failure: `error` set (no started / no rows).
  const factory AppEvent.messageListWindowComplete({
    required String requestId,
    required String accountId,
    required String folderName,
    required String messageListSort,
    String? error,
  }) = AppEvent_MessageListWindowComplete;
  const factory AppEvent.commandResult({
    String? requestId,
    required bool ok,
    String? error,
  }) = AppEvent_CommandResult;

  /// Kind 0 metadata resolved for a peer pubkey (async follow-up to message/folder list).
  const factory AppEvent.nostrProfileUpdated({
    required String accountId,

    /// Lowercase hex pubkey (folder id for DM conversations).
    required String pubkeyHex,

    /// npub (bech32) for display fallback.
    required String npub,
    String? displayName,
    String? nip05,
    String? picture,
  }) = AppEvent_NostrProfileUpdated;

  /// Folder list snapshot failed (e.g. timeout); [folderFound] rows are not cleared.
  const factory AppEvent.folderListFailed({
    required String accountId,
    required String message,
  }) = AppEvent_FolderListFailed;
}

/// Message list row summary for list windows (same fields as mail `MessageSummaryJson`).
class MessageListRowSummary {
  final String id;
  final String from;
  final String subject;
  final PlatformInt64? dateMs;
  final bool isRead;
  final bool markedForDeletion;
  final String? nostrSenderPubkeyHex;

  const MessageListRowSummary({
    required this.id,
    required this.from,
    required this.subject,
    this.dateMs,
    required this.isRead,
    required this.markedForDeletion,
    this.nostrSenderPubkeyHex,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      from.hashCode ^
      subject.hashCode ^
      dateMs.hashCode ^
      isRead.hashCode ^
      markedForDeletion.hashCode ^
      nostrSenderPubkeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageListRowSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          from == other.from &&
          subject == other.subject &&
          dateMs == other.dateMs &&
          isRead == other.isRead &&
          markedForDeletion == other.markedForDeletion &&
          nostrSenderPubkeyHex == other.nostrSenderPubkeyHex;
}

/// One row for the **Available** folder tab (see `MailFoldersSnapshot::subscription_pane`).
class SubscriptionAvailableRow {
  final String id;
  final bool isSubscribed;
  final String? displayName;
  final int? unread;
  final bool allowUnsubscribe;

  const SubscriptionAvailableRow({
    required this.id,
    required this.isSubscribed,
    this.displayName,
    this.unread,
    required this.allowUnsubscribe,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      isSubscribed.hashCode ^
      displayName.hashCode ^
      unread.hashCode ^
      allowUnsubscribe.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubscriptionAvailableRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          isSubscribed == other.isSubscribed &&
          displayName == other.displayName &&
          unread == other.unread &&
          allowUnsubscribe == other.allowUnsubscribe;
}
