// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `config_xml_path`, `default_message_list_sort`, `load_frb_config_struct`, `mail_body_path_message_id_segment`, `merge_accounts_from_tagliacarte_xml`, `read_config`, `write_config`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

Future<String> frbLoadConfigJson({required String path}) =>
    RustLib.instance.api.crateFrbApiFrbLoadConfigJson(path: path);

Future<void> frbSaveConfigJson({
  required String path,
  required String configJson,
}) => RustLib.instance.api.crateFrbApiFrbSaveConfigJson(
  path: path,
  configJson: configJson,
);

Future<String> frbUpsertAccount({
  required String path,
  required String accountJson,
}) => RustLib.instance.api.crateFrbApiFrbUpsertAccount(
  path: path,
  accountJson: accountJson,
);

Future<String> frbRemoveAccount({
  required String path,
  required String accountId,
}) => RustLib.instance.api.crateFrbApiFrbRemoveAccount(
  path: path,
  accountId: accountId,
);

/// `credential_key`: vault id (`s1`, …). Empty uses `store_uri` (legacy).
Future<String> frbListMailFolders({
  required String storeUri,
  required String credentialKey,
  required bool useKeychain,
}) => RustLib.instance.api.crateFrbApiFrbListMailFolders(
  storeUri: storeUri,
  credentialKey: credentialKey,
  useKeychain: useKeychain,
);

Future<bool> frbImapTakeFolderListStale({
  required String storeUri,
  required String credentialKey,
  required bool useKeychain,
}) => RustLib.instance.api.crateFrbApiFrbImapTakeFolderListStale(
  storeUri: storeUri,
  credentialKey: credentialKey,
  useKeychain: useKeychain,
);

Future<void> frbImapConfigureIdleThreshold({
  required String storeUri,
  required String credentialKey,
  required bool useKeychain,
  required int minIdleSeconds,
}) => RustLib.instance.api.crateFrbApiFrbImapConfigureIdleThreshold(
  storeUri: storeUri,
  credentialKey: credentialKey,
  useKeychain: useKeychain,
  minIdleSeconds: minIdleSeconds,
);

Future<void> frbCreateMailFolder({
  required String storeUri,
  required String credentialKey,
  required String folderPath,
  required bool useKeychain,
}) => RustLib.instance.api.crateFrbApiFrbCreateMailFolder(
  storeUri: storeUri,
  credentialKey: credentialKey,
  folderPath: folderPath,
  useKeychain: useKeychain,
);

Future<void> frbRenameMailFolder({
  required String storeUri,
  required String credentialKey,
  required String oldName,
  required String newName,
  required bool useKeychain,
}) => RustLib.instance.api.crateFrbApiFrbRenameMailFolder(
  storeUri: storeUri,
  credentialKey: credentialKey,
  oldName: oldName,
  newName: newName,
  useKeychain: useKeychain,
);

Future<void> frbDeleteMailFolder({
  required String storeUri,
  required String credentialKey,
  required String folderName,
  required bool useKeychain,
}) => RustLib.instance.api.crateFrbApiFrbDeleteMailFolder(
  storeUri: storeUri,
  credentialKey: credentialKey,
  folderName: folderName,
  useKeychain: useKeychain,
);

Future<String> frbListFolderMessages({
  required String storeUri,
  required String credentialKey,
  required String folderName,
  required int skip,
  required int limit,
  required bool useKeychain,
}) => RustLib.instance.api.crateFrbApiFrbListFolderMessages(
  storeUri: storeUri,
  credentialKey: credentialKey,
  folderName: folderName,
  skip: skip,
  limit: limit,
  useKeychain: useKeychain,
);

/// List one page of message summaries in **ascending** order for [message_list_sort]. JSON includes
/// `total`, `startIndex`, `messages`, `listStrategy` (`imapSort` or `fullScan`).
Future<String> frbListFolderMessagesWindow({
  required String storeUri,
  required String credentialKey,
  required String folderName,
  required int startIndex,
  required int limit,
  required String messageListSort,
  required bool useKeychain,
}) => RustLib.instance.api.crateFrbApiFrbListFolderMessagesWindow(
  storeUri: storeUri,
  credentialKey: credentialKey,
  folderName: folderName,
  startIndex: startIndex,
  limit: limit,
  messageListSort: messageListSort,
  useKeychain: useKeychain,
);

Future<String> frbGetFolderMessage({
  required String storeUri,
  required String credentialKey,
  required String folderName,
  required String messageId,
  required bool useKeychain,
}) => RustLib.instance.api.crateFrbApiFrbGetFolderMessage(
  storeUri: storeUri,
  credentialKey: credentialKey,
  folderName: folderName,
  messageId: messageId,
  useKeychain: useKeychain,
);

Future<void> frbMarkFolderMessageRead({
  required String storeUri,
  required String credentialKey,
  required String folderName,
  required String messageId,
  required bool useKeychain,
}) => RustLib.instance.api.crateFrbApiFrbMarkFolderMessageRead(
  storeUri: storeUri,
  credentialKey: credentialKey,
  folderName: folderName,
  messageId: messageId,
  useKeychain: useKeychain,
);

/// JSON: `{ results: [{ id, ok, error? }], okCount, failedCount }`. Cross-store move deletes source only after successful append.
Future<String> frbTransferMailMessages({
  required String sourceStoreUri,
  required String sourceCredentialKey,
  required String sourceFolder,
  required String destStoreUri,
  required String destCredentialKey,
  required String destFolder,
  required List<String> messageIds,
  required bool isMove,
  required bool useKeychain,
}) => RustLib.instance.api.crateFrbApiFrbTransferMailMessages(
  sourceStoreUri: sourceStoreUri,
  sourceCredentialKey: sourceCredentialKey,
  sourceFolder: sourceFolder,
  destStoreUri: destStoreUri,
  destCredentialKey: destCredentialKey,
  destFolder: destFolder,
  messageIds: messageIds,
  isMove: isMove,
  useKeychain: useKeychain,
);

Future<void> frbExpungeMailFolder({
  required String storeUri,
  required String credentialKey,
  required String folderName,
  required bool useKeychain,
}) => RustLib.instance.api.crateFrbApiFrbExpungeMailFolder(
  storeUri: storeUri,
  credentialKey: credentialKey,
  folderName: folderName,
  useKeychain: useKeychain,
);

/// Set whether the mail-body HTTPS server requires a **client certificate** (mutual TLS).
/// Default is **true** (strict). Call with **false** before [`frb_mail_body_server_init`] when the
/// embedded WebView cannot present [`client_cert_pem`] yet (loopback TLS remains enabled).
Future<void> frbMailBodySetTlsRequireClientCert({required bool require}) =>
    RustLib.instance.api.crateFrbApiFrbMailBodySetTlsRequireClientCert(
      require: require,
    );

/// Fetch one IMAP MIME part by section (decoded). JSON: `{ "bytesBase64": "..." }`.
/// Start loopback mTLS server if needed. JSON includes `enforcesClientCert`, PEM material, `baseUrl`.
Future<String> frbMailBodyServerInit() =>
    RustLib.instance.api.crateFrbApiFrbMailBodyServerInit();

/// Register store for `/view/{key}/...` URLs. Call after `frb_mail_body_server_init`. Returns opaque `storeKey`.
Future<String> frbMailBodyRegisterStore({
  required String storeUri,
  required String credentialKey,
  required bool useKeychain,
}) => RustLib.instance.api.crateFrbApiFrbMailBodyRegisterStore(
  storeUri: storeUri,
  credentialKey: credentialKey,
  useKeychain: useKeychain,
);

/// Build message body URL. `message_id` is IMAP UID as decimal digits, or any store-specific id (percent-encoded in path).
/// `folder_name` is raw mailbox name; `extra_query` like `fg=fff&bg=000`.
Future<String> frbMailBodyMessageUrl({
  required String storeKey,
  required String folderName,
  required String messageId,
  required String extraQuery,
}) => RustLib.instance.api.crateFrbApiFrbMailBodyMessageUrl(
  storeKey: storeKey,
  folderName: folderName,
  messageId: messageId,
  extraQuery: extraQuery,
);

Future<String> frbFetchFolderMessagePart({
  required String storeUri,
  required String credentialKey,
  required String folderName,
  required String messageId,
  required String imapSection,
  required String transferEncoding,
  required bool useKeychain,
}) => RustLib.instance.api.crateFrbApiFrbFetchFolderMessagePart(
  storeUri: storeUri,
  credentialKey: credentialKey,
  folderName: folderName,
  messageId: messageId,
  imapSection: imapSection,
  transferEncoding: transferEncoding,
  useKeychain: useKeychain,
);

/// Persists secrets under `credential_id` (store XML id, e.g. `s1`). Invalidates the IMAP cache for `store_uri`.
Future<void> frbSaveStoreCredential({
  required String credentialId,
  required String storeUri,
  required String username,
  required String password,
  required bool useKeychain,
}) => RustLib.instance.api.crateFrbApiFrbSaveStoreCredential(
  credentialId: credentialId,
  storeUri: storeUri,
  username: username,
  password: password,
  useKeychain: useKeychain,
);

/// Outbound transport credentials (e.g. SMTP), keyed by transport id (`t1`).
Future<void> frbSaveTransportCredential({
  required String transportId,
  required String username,
  required String password,
  required bool useKeychain,
}) => RustLib.instance.api.crateFrbApiFrbSaveTransportCredential(
  transportId: transportId,
  username: username,
  password: password,
  useKeychain: useKeychain,
);

/// Subscribe to app-level mail events (folder lists, connection status, command results).
/// Call once after [RustLib.init]. [config_xml_path] is the same `config.xml` path Flutter uses.
Stream<String> frbSessionStart({required String configXmlPath}) => RustLib
    .instance
    .api
    .crateFrbApiFrbSessionStart(configXmlPath: configXmlPath);

/// Fire-and-forget session command (JSON with `type`: markRead, refreshFolders, transferMessages).
Future<void> frbSessionCommand({required String commandJson}) =>
    RustLib.instance.api.crateFrbApiFrbSessionCommand(commandJson: commandJson);

class FrbAccount {
  final String id;
  final String label;
  final String backendType;
  final String storeUri;
  final List<String> transportIds;
  final String? transportUri;
  final String? username;
  final String? host;
  final int? port;
  final String? security;
  final String? path;
  final String? email;
  final String? avatarUrl;
  final String? lastFolder;
  final String? lastMessageId;

  /// Minimum seconds of connection quiet before issuing IDLE; `None` → default 120.
  final int? imapIdleMinIdleSeconds;

  const FrbAccount({
    required this.id,
    required this.label,
    required this.backendType,
    required this.storeUri,
    required this.transportIds,
    this.transportUri,
    this.username,
    this.host,
    this.port,
    this.security,
    this.path,
    this.email,
    this.avatarUrl,
    this.lastFolder,
    this.lastMessageId,
    this.imapIdleMinIdleSeconds,
  });

  static Future<FrbAccount> default_() =>
      RustLib.instance.api.crateFrbApiFrbAccountDefault();

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      backendType.hashCode ^
      storeUri.hashCode ^
      transportIds.hashCode ^
      transportUri.hashCode ^
      username.hashCode ^
      host.hashCode ^
      port.hashCode ^
      security.hashCode ^
      path.hashCode ^
      email.hashCode ^
      avatarUrl.hashCode ^
      lastFolder.hashCode ^
      lastMessageId.hashCode ^
      imapIdleMinIdleSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbAccount &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          backendType == other.backendType &&
          storeUri == other.storeUri &&
          transportIds == other.transportIds &&
          transportUri == other.transportUri &&
          username == other.username &&
          host == other.host &&
          port == other.port &&
          security == other.security &&
          path == other.path &&
          email == other.email &&
          avatarUrl == other.avatarUrl &&
          lastFolder == other.lastFolder &&
          lastMessageId == other.lastMessageId &&
          imapIdleMinIdleSeconds == other.imapIdleMinIdleSeconds;
}

class FrbConfig {
  final List<FrbAccount> accounts;
  final List<FrbTransport> transports;
  final String? selectedStoreId;
  final String dateFormat;
  final String resourcePolicy;
  final bool useKeychain;
  final bool loadRemoteImages;
  final bool threadedView;
  final bool quoteOriginal;
  final String deleteMode;
  final String trashFolderName;

  /// Symbolic message list sort, e.g. `date_desc`, `from_asc`, `subject_asc`.
  final String messageListSort;

  /// In-app / OS new-mail notifications (toasts, local notifications).
  final bool notifyNewMessages;

  const FrbConfig({
    required this.accounts,
    required this.transports,
    this.selectedStoreId,
    required this.dateFormat,
    required this.resourcePolicy,
    required this.useKeychain,
    required this.loadRemoteImages,
    required this.threadedView,
    required this.quoteOriginal,
    required this.deleteMode,
    required this.trashFolderName,
    required this.messageListSort,
    required this.notifyNewMessages,
  });

  static Future<FrbConfig> default_() =>
      RustLib.instance.api.crateFrbApiFrbConfigDefault();

  @override
  int get hashCode =>
      accounts.hashCode ^
      transports.hashCode ^
      selectedStoreId.hashCode ^
      dateFormat.hashCode ^
      resourcePolicy.hashCode ^
      useKeychain.hashCode ^
      loadRemoteImages.hashCode ^
      threadedView.hashCode ^
      quoteOriginal.hashCode ^
      deleteMode.hashCode ^
      trashFolderName.hashCode ^
      messageListSort.hashCode ^
      notifyNewMessages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbConfig &&
          runtimeType == other.runtimeType &&
          accounts == other.accounts &&
          transports == other.transports &&
          selectedStoreId == other.selectedStoreId &&
          dateFormat == other.dateFormat &&
          resourcePolicy == other.resourcePolicy &&
          useKeychain == other.useKeychain &&
          loadRemoteImages == other.loadRemoteImages &&
          threadedView == other.threadedView &&
          quoteOriginal == other.quoteOriginal &&
          deleteMode == other.deleteMode &&
          trashFolderName == other.trashFolderName &&
          messageListSort == other.messageListSort &&
          notifyNewMessages == other.notifyNewMessages;
}

class FrbTransport {
  final String id;
  final String transportType;
  final String displayName;
  final String host;
  final int port;
  final String security;
  final String transportUri;

  const FrbTransport({
    required this.id,
    required this.transportType,
    required this.displayName,
    required this.host,
    required this.port,
    required this.security,
    required this.transportUri,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      transportType.hashCode ^
      displayName.hashCode ^
      host.hashCode ^
      port.hashCode ^
      security.hashCode ^
      transportUri.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbTransport &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          transportType == other.transportType &&
          displayName == other.displayName &&
          host == other.host &&
          port == other.port &&
          security == other.security &&
          transportUri == other.transportUri;
}
