// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'frb_api.dart';
import 'frb_api/frb_json.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -746244738;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'tagliacarte_app',
        ioDirectory: '../app/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateFrbApiFrbJsonFormatFrbConfigJson({
    required FrbConfig cfg,
  });

  Future<FrbAccount> crateFrbApiFrbAccountDefault();

  Future<FrbConfig> crateFrbApiFrbConfigDefault();

  Future<FrbConfigParse> crateFrbApiFrbJsonFrbConfigParseDefault();

  Future<FrbConfigParse> crateFrbApiFrbJsonFrbConfigParseFromBridgeFields({
    required FrbConfig config,
    required List<CfgStack> stack,
    String? err,
  });

  Future<FrbConfigParse> crateFrbApiFrbJsonFrbConfigParseNew();

  Future<void> crateFrbApiFrbCreateMailFolder({
    required String storeUri,
    required String credentialKey,
    required String folderPath,
    required bool useKeychain,
  });

  Future<void> crateFrbApiFrbDeleteMailFolder({
    required String storeUri,
    required String credentialKey,
    required String folderName,
    required bool useKeychain,
  });

  Future<void> crateFrbApiFrbExpungeMailFolder({
    required String storeUri,
    required String credentialKey,
    required String folderName,
    required bool useKeychain,
  });

  Future<String> crateFrbApiFrbFetchFolderMessagePart({
    required String storeUri,
    required String credentialKey,
    required String folderName,
    required String messageId,
    required String imapSection,
    required String transferEncoding,
    required bool useKeychain,
  });

  Future<String> crateFrbApiFrbGetFolderMessage({
    required String storeUri,
    required String credentialKey,
    required String folderName,
    required String messageId,
    required bool useKeychain,
  });

  Future<void> crateFrbApiFrbImapConfigureIdleThreshold({
    required String storeUri,
    required String credentialKey,
    required bool useKeychain,
    required int minIdleSeconds,
  });

  Future<bool> crateFrbApiFrbImapTakeFolderListStale({
    required String storeUri,
    required String credentialKey,
    required bool useKeychain,
  });

  Future<String> crateFrbApiFrbListFolderMessages({
    required String storeUri,
    required String credentialKey,
    required String folderName,
    required int skip,
    required int limit,
    required bool useKeychain,
  });

  Future<String> crateFrbApiFrbListFolderMessagesWindow({
    required String storeUri,
    required String credentialKey,
    required String folderName,
    required int startIndex,
    required int limit,
    required String messageListSort,
    required bool useKeychain,
  });

  Future<String> crateFrbApiFrbListMailFolders({
    required String storeUri,
    required String credentialKey,
    required bool useKeychain,
  });

  Future<String> crateFrbApiFrbLoadConfigJson({required String path});

  Future<String> crateFrbApiFrbMailBodyMessageUrl({
    required String storeKey,
    required String folderName,
    required String messageId,
    required String extraQuery,
  });

  Future<String> crateFrbApiFrbMailBodyRegisterStore({
    required String storeUri,
    required String credentialKey,
    required bool useKeychain,
  });

  Future<String> crateFrbApiFrbMailBodyServerInit();

  Future<void> crateFrbApiFrbMailBodySetTlsRequireClientCert({
    required bool require,
  });

  Future<void> crateFrbApiFrbMarkFolderMessageRead({
    required String storeUri,
    required String credentialKey,
    required String folderName,
    required String messageId,
    required bool useKeychain,
  });

  Future<String> crateFrbApiFrbNostrGenerateKeypairJson();

  Future<String> crateFrbApiFrbNostrGetPublicKeyFromSecret({
    required String secret,
  });

  Future<String> crateFrbApiFrbNostrHexToNpub({required String hexPubkey});

  Future<void> crateFrbApiFrbNostrPublishProfile({
    required String path,
    required String accountId,
  });

  Future<String> crateFrbApiFrbNostrSecretKeyToHex({required String input});

  Future<void> crateFrbApiFrbNostrSyncRemoteProfile({
    required String path,
    required String accountId,
  });

  Future<String> crateFrbApiFrbRemoveAccount({
    required String path,
    required String accountId,
  });

  Future<void> crateFrbApiFrbRenameMailFolder({
    required String storeUri,
    required String credentialKey,
    required String oldName,
    required String newName,
    required bool useKeychain,
  });

  Future<void> crateFrbApiFrbSaveConfigJson({
    required String path,
    required String configJson,
  });

  Future<void> crateFrbApiFrbSaveStoreCredential({
    required String credentialId,
    required String storeUri,
    required String username,
    required String password,
    required bool useKeychain,
  });

  Future<void> crateFrbApiFrbSaveTransportCredential({
    required String transportId,
    required String username,
    required String password,
    required bool useKeychain,
  });

  Future<void> crateFrbApiFrbSessionCommand({required String commandJson});

  Future<String> crateFrbApiFrbSessionGetFolderMessage({
    required String accountId,
    required String folderName,
    required String messageId,
  });

  Future<String> crateFrbApiFrbSessionListMessagesWindow({
    required String accountId,
    required String folderName,
    required int startIndex,
    required int limit,
    required String messageListSort,
  });

  Future<String> crateFrbApiFrbSessionRegisterMailBodyStore({
    required String accountId,
  });

  Stream<String> crateFrbApiFrbSessionStart({required String configXmlPath});

  Future<String> crateFrbApiFrbTransferMailMessages({
    required String sourceStoreUri,
    required String sourceCredentialKey,
    required String sourceFolder,
    required String destStoreUri,
    required String destCredentialKey,
    required String destFolder,
    required List<String> messageIds,
    required bool isMove,
    required bool useKeychain,
  });

  Future<String> crateFrbApiFrbUpsertAccount({
    required String path,
    required String accountJson,
  });

  Future<FrbAccount> crateFrbApiFrbJsonParseFrbAccountJson({
    required String input,
  });

  Future<FrbConfig> crateFrbApiFrbJsonParseFrbConfigJson({
    required String input,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateFrbApiFrbJsonFormatFrbConfigJson({
    required FrbConfig cfg,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_box_autoadd_frb_config(cfg);
          return wire.wire__crate__frb_api__frb_json__format_frb_config_json(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiFrbJsonFormatFrbConfigJsonConstMeta,
        argValues: [cfg],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbJsonFormatFrbConfigJsonConstMeta =>
      const TaskConstMeta(
        debugName: "format_frb_config_json",
        argNames: ["cfg"],
      );

  @override
  Future<FrbAccount> crateFrbApiFrbAccountDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__frb_api__frb_account_default(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_frb_account,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiFrbAccountDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbAccountDefaultConstMeta =>
      const TaskConstMeta(debugName: "frb_account_default", argNames: []);

  @override
  Future<FrbConfig> crateFrbApiFrbConfigDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__frb_api__frb_config_default(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_frb_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiFrbConfigDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbConfigDefaultConstMeta =>
      const TaskConstMeta(debugName: "frb_config_default", argNames: []);

  @override
  Future<FrbConfigParse> crateFrbApiFrbJsonFrbConfigParseDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__frb_api__frb_json__frb_config_parse_default(
            port_,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_frb_config_parse,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiFrbJsonFrbConfigParseDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbJsonFrbConfigParseDefaultConstMeta =>
      const TaskConstMeta(debugName: "frb_config_parse_default", argNames: []);

  @override
  Future<FrbConfigParse> crateFrbApiFrbJsonFrbConfigParseFromBridgeFields({
    required FrbConfig config,
    required List<CfgStack> stack,
    String? err,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_box_autoadd_frb_config(config);
          var arg1 = cst_encode_list_cfg_stack(stack);
          var arg2 = cst_encode_opt_String(err);
          return wire
              .wire__crate__frb_api__frb_json__frb_config_parse_from_bridge_fields(
                port_,
                arg0,
                arg1,
                arg2,
              );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_frb_config_parse,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiFrbJsonFrbConfigParseFromBridgeFieldsConstMeta,
        argValues: [config, stack, err],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateFrbApiFrbJsonFrbConfigParseFromBridgeFieldsConstMeta =>
      const TaskConstMeta(
        debugName: "frb_config_parse_from_bridge_fields",
        argNames: ["config", "stack", "err"],
      );

  @override
  Future<FrbConfigParse> crateFrbApiFrbJsonFrbConfigParseNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__frb_api__frb_json__frb_config_parse_new(
            port_,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_frb_config_parse,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiFrbJsonFrbConfigParseNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbJsonFrbConfigParseNewConstMeta =>
      const TaskConstMeta(debugName: "frb_config_parse_new", argNames: []);

  @override
  Future<void> crateFrbApiFrbCreateMailFolder({
    required String storeUri,
    required String credentialKey,
    required String folderPath,
    required bool useKeychain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(storeUri);
          var arg1 = cst_encode_String(credentialKey);
          var arg2 = cst_encode_String(folderPath);
          var arg3 = cst_encode_bool(useKeychain);
          return wire.wire__crate__frb_api__frb_create_mail_folder(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbCreateMailFolderConstMeta,
        argValues: [storeUri, credentialKey, folderPath, useKeychain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbCreateMailFolderConstMeta =>
      const TaskConstMeta(
        debugName: "frb_create_mail_folder",
        argNames: ["storeUri", "credentialKey", "folderPath", "useKeychain"],
      );

  @override
  Future<void> crateFrbApiFrbDeleteMailFolder({
    required String storeUri,
    required String credentialKey,
    required String folderName,
    required bool useKeychain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(storeUri);
          var arg1 = cst_encode_String(credentialKey);
          var arg2 = cst_encode_String(folderName);
          var arg3 = cst_encode_bool(useKeychain);
          return wire.wire__crate__frb_api__frb_delete_mail_folder(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbDeleteMailFolderConstMeta,
        argValues: [storeUri, credentialKey, folderName, useKeychain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbDeleteMailFolderConstMeta =>
      const TaskConstMeta(
        debugName: "frb_delete_mail_folder",
        argNames: ["storeUri", "credentialKey", "folderName", "useKeychain"],
      );

  @override
  Future<void> crateFrbApiFrbExpungeMailFolder({
    required String storeUri,
    required String credentialKey,
    required String folderName,
    required bool useKeychain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(storeUri);
          var arg1 = cst_encode_String(credentialKey);
          var arg2 = cst_encode_String(folderName);
          var arg3 = cst_encode_bool(useKeychain);
          return wire.wire__crate__frb_api__frb_expunge_mail_folder(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbExpungeMailFolderConstMeta,
        argValues: [storeUri, credentialKey, folderName, useKeychain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbExpungeMailFolderConstMeta =>
      const TaskConstMeta(
        debugName: "frb_expunge_mail_folder",
        argNames: ["storeUri", "credentialKey", "folderName", "useKeychain"],
      );

  @override
  Future<String> crateFrbApiFrbFetchFolderMessagePart({
    required String storeUri,
    required String credentialKey,
    required String folderName,
    required String messageId,
    required String imapSection,
    required String transferEncoding,
    required bool useKeychain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(storeUri);
          var arg1 = cst_encode_String(credentialKey);
          var arg2 = cst_encode_String(folderName);
          var arg3 = cst_encode_String(messageId);
          var arg4 = cst_encode_String(imapSection);
          var arg5 = cst_encode_String(transferEncoding);
          var arg6 = cst_encode_bool(useKeychain);
          return wire.wire__crate__frb_api__frb_fetch_folder_message_part(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
            arg5,
            arg6,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbFetchFolderMessagePartConstMeta,
        argValues: [
          storeUri,
          credentialKey,
          folderName,
          messageId,
          imapSection,
          transferEncoding,
          useKeychain,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbFetchFolderMessagePartConstMeta =>
      const TaskConstMeta(
        debugName: "frb_fetch_folder_message_part",
        argNames: [
          "storeUri",
          "credentialKey",
          "folderName",
          "messageId",
          "imapSection",
          "transferEncoding",
          "useKeychain",
        ],
      );

  @override
  Future<String> crateFrbApiFrbGetFolderMessage({
    required String storeUri,
    required String credentialKey,
    required String folderName,
    required String messageId,
    required bool useKeychain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(storeUri);
          var arg1 = cst_encode_String(credentialKey);
          var arg2 = cst_encode_String(folderName);
          var arg3 = cst_encode_String(messageId);
          var arg4 = cst_encode_bool(useKeychain);
          return wire.wire__crate__frb_api__frb_get_folder_message(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbGetFolderMessageConstMeta,
        argValues: [
          storeUri,
          credentialKey,
          folderName,
          messageId,
          useKeychain,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbGetFolderMessageConstMeta =>
      const TaskConstMeta(
        debugName: "frb_get_folder_message",
        argNames: [
          "storeUri",
          "credentialKey",
          "folderName",
          "messageId",
          "useKeychain",
        ],
      );

  @override
  Future<void> crateFrbApiFrbImapConfigureIdleThreshold({
    required String storeUri,
    required String credentialKey,
    required bool useKeychain,
    required int minIdleSeconds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(storeUri);
          var arg1 = cst_encode_String(credentialKey);
          var arg2 = cst_encode_bool(useKeychain);
          var arg3 = cst_encode_u_32(minIdleSeconds);
          return wire.wire__crate__frb_api__frb_imap_configure_idle_threshold(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbImapConfigureIdleThresholdConstMeta,
        argValues: [storeUri, credentialKey, useKeychain, minIdleSeconds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbImapConfigureIdleThresholdConstMeta =>
      const TaskConstMeta(
        debugName: "frb_imap_configure_idle_threshold",
        argNames: [
          "storeUri",
          "credentialKey",
          "useKeychain",
          "minIdleSeconds",
        ],
      );

  @override
  Future<bool> crateFrbApiFrbImapTakeFolderListStale({
    required String storeUri,
    required String credentialKey,
    required bool useKeychain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(storeUri);
          var arg1 = cst_encode_String(credentialKey);
          var arg2 = cst_encode_bool(useKeychain);
          return wire.wire__crate__frb_api__frb_imap_take_folder_list_stale(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiFrbImapTakeFolderListStaleConstMeta,
        argValues: [storeUri, credentialKey, useKeychain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbImapTakeFolderListStaleConstMeta =>
      const TaskConstMeta(
        debugName: "frb_imap_take_folder_list_stale",
        argNames: ["storeUri", "credentialKey", "useKeychain"],
      );

  @override
  Future<String> crateFrbApiFrbListFolderMessages({
    required String storeUri,
    required String credentialKey,
    required String folderName,
    required int skip,
    required int limit,
    required bool useKeychain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(storeUri);
          var arg1 = cst_encode_String(credentialKey);
          var arg2 = cst_encode_String(folderName);
          var arg3 = cst_encode_i_32(skip);
          var arg4 = cst_encode_i_32(limit);
          var arg5 = cst_encode_bool(useKeychain);
          return wire.wire__crate__frb_api__frb_list_folder_messages(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
            arg5,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbListFolderMessagesConstMeta,
        argValues: [
          storeUri,
          credentialKey,
          folderName,
          skip,
          limit,
          useKeychain,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbListFolderMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "frb_list_folder_messages",
        argNames: [
          "storeUri",
          "credentialKey",
          "folderName",
          "skip",
          "limit",
          "useKeychain",
        ],
      );

  @override
  Future<String> crateFrbApiFrbListFolderMessagesWindow({
    required String storeUri,
    required String credentialKey,
    required String folderName,
    required int startIndex,
    required int limit,
    required String messageListSort,
    required bool useKeychain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(storeUri);
          var arg1 = cst_encode_String(credentialKey);
          var arg2 = cst_encode_String(folderName);
          var arg3 = cst_encode_i_32(startIndex);
          var arg4 = cst_encode_i_32(limit);
          var arg5 = cst_encode_String(messageListSort);
          var arg6 = cst_encode_bool(useKeychain);
          return wire.wire__crate__frb_api__frb_list_folder_messages_window(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
            arg5,
            arg6,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbListFolderMessagesWindowConstMeta,
        argValues: [
          storeUri,
          credentialKey,
          folderName,
          startIndex,
          limit,
          messageListSort,
          useKeychain,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbListFolderMessagesWindowConstMeta =>
      const TaskConstMeta(
        debugName: "frb_list_folder_messages_window",
        argNames: [
          "storeUri",
          "credentialKey",
          "folderName",
          "startIndex",
          "limit",
          "messageListSort",
          "useKeychain",
        ],
      );

  @override
  Future<String> crateFrbApiFrbListMailFolders({
    required String storeUri,
    required String credentialKey,
    required bool useKeychain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(storeUri);
          var arg1 = cst_encode_String(credentialKey);
          var arg2 = cst_encode_bool(useKeychain);
          return wire.wire__crate__frb_api__frb_list_mail_folders(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbListMailFoldersConstMeta,
        argValues: [storeUri, credentialKey, useKeychain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbListMailFoldersConstMeta =>
      const TaskConstMeta(
        debugName: "frb_list_mail_folders",
        argNames: ["storeUri", "credentialKey", "useKeychain"],
      );

  @override
  Future<String> crateFrbApiFrbLoadConfigJson({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(path);
          return wire.wire__crate__frb_api__frb_load_config_json(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiFrbLoadConfigJsonConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbLoadConfigJsonConstMeta =>
      const TaskConstMeta(
        debugName: "frb_load_config_json",
        argNames: ["path"],
      );

  @override
  Future<String> crateFrbApiFrbMailBodyMessageUrl({
    required String storeKey,
    required String folderName,
    required String messageId,
    required String extraQuery,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(storeKey);
          var arg1 = cst_encode_String(folderName);
          var arg2 = cst_encode_String(messageId);
          var arg3 = cst_encode_String(extraQuery);
          return wire.wire__crate__frb_api__frb_mail_body_message_url(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbMailBodyMessageUrlConstMeta,
        argValues: [storeKey, folderName, messageId, extraQuery],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbMailBodyMessageUrlConstMeta =>
      const TaskConstMeta(
        debugName: "frb_mail_body_message_url",
        argNames: ["storeKey", "folderName", "messageId", "extraQuery"],
      );

  @override
  Future<String> crateFrbApiFrbMailBodyRegisterStore({
    required String storeUri,
    required String credentialKey,
    required bool useKeychain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(storeUri);
          var arg1 = cst_encode_String(credentialKey);
          var arg2 = cst_encode_bool(useKeychain);
          return wire.wire__crate__frb_api__frb_mail_body_register_store(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbMailBodyRegisterStoreConstMeta,
        argValues: [storeUri, credentialKey, useKeychain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbMailBodyRegisterStoreConstMeta =>
      const TaskConstMeta(
        debugName: "frb_mail_body_register_store",
        argNames: ["storeUri", "credentialKey", "useKeychain"],
      );

  @override
  Future<String> crateFrbApiFrbMailBodyServerInit() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__frb_api__frb_mail_body_server_init(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbMailBodyServerInitConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbMailBodyServerInitConstMeta =>
      const TaskConstMeta(debugName: "frb_mail_body_server_init", argNames: []);

  @override
  Future<void> crateFrbApiFrbMailBodySetTlsRequireClientCert({
    required bool require,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_bool(require);
          return wire
              .wire__crate__frb_api__frb_mail_body_set_tls_require_client_cert(
                port_,
                arg0,
              );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiFrbMailBodySetTlsRequireClientCertConstMeta,
        argValues: [require],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbMailBodySetTlsRequireClientCertConstMeta =>
      const TaskConstMeta(
        debugName: "frb_mail_body_set_tls_require_client_cert",
        argNames: ["require"],
      );

  @override
  Future<void> crateFrbApiFrbMarkFolderMessageRead({
    required String storeUri,
    required String credentialKey,
    required String folderName,
    required String messageId,
    required bool useKeychain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(storeUri);
          var arg1 = cst_encode_String(credentialKey);
          var arg2 = cst_encode_String(folderName);
          var arg3 = cst_encode_String(messageId);
          var arg4 = cst_encode_bool(useKeychain);
          return wire.wire__crate__frb_api__frb_mark_folder_message_read(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbMarkFolderMessageReadConstMeta,
        argValues: [
          storeUri,
          credentialKey,
          folderName,
          messageId,
          useKeychain,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbMarkFolderMessageReadConstMeta =>
      const TaskConstMeta(
        debugName: "frb_mark_folder_message_read",
        argNames: [
          "storeUri",
          "credentialKey",
          "folderName",
          "messageId",
          "useKeychain",
        ],
      );

  @override
  Future<String> crateFrbApiFrbNostrGenerateKeypairJson() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__frb_api__frb_nostr_generate_keypair_json(
            port_,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbNostrGenerateKeypairJsonConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbNostrGenerateKeypairJsonConstMeta =>
      const TaskConstMeta(
        debugName: "frb_nostr_generate_keypair_json",
        argNames: [],
      );

  @override
  Future<String> crateFrbApiFrbNostrGetPublicKeyFromSecret({
    required String secret,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(secret);
          return wire
              .wire__crate__frb_api__frb_nostr_get_public_key_from_secret(
                port_,
                arg0,
              );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbNostrGetPublicKeyFromSecretConstMeta,
        argValues: [secret],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbNostrGetPublicKeyFromSecretConstMeta =>
      const TaskConstMeta(
        debugName: "frb_nostr_get_public_key_from_secret",
        argNames: ["secret"],
      );

  @override
  Future<String> crateFrbApiFrbNostrHexToNpub({required String hexPubkey}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(hexPubkey);
          return wire.wire__crate__frb_api__frb_nostr_hex_to_npub(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbNostrHexToNpubConstMeta,
        argValues: [hexPubkey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbNostrHexToNpubConstMeta =>
      const TaskConstMeta(
        debugName: "frb_nostr_hex_to_npub",
        argNames: ["hexPubkey"],
      );

  @override
  Future<void> crateFrbApiFrbNostrPublishProfile({
    required String path,
    required String accountId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(path);
          var arg1 = cst_encode_String(accountId);
          return wire.wire__crate__frb_api__frb_nostr_publish_profile(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbNostrPublishProfileConstMeta,
        argValues: [path, accountId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbNostrPublishProfileConstMeta =>
      const TaskConstMeta(
        debugName: "frb_nostr_publish_profile",
        argNames: ["path", "accountId"],
      );

  @override
  Future<String> crateFrbApiFrbNostrSecretKeyToHex({required String input}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(input);
          return wire.wire__crate__frb_api__frb_nostr_secret_key_to_hex(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbNostrSecretKeyToHexConstMeta,
        argValues: [input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbNostrSecretKeyToHexConstMeta =>
      const TaskConstMeta(
        debugName: "frb_nostr_secret_key_to_hex",
        argNames: ["input"],
      );

  @override
  Future<void> crateFrbApiFrbNostrSyncRemoteProfile({
    required String path,
    required String accountId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(path);
          var arg1 = cst_encode_String(accountId);
          return wire.wire__crate__frb_api__frb_nostr_sync_remote_profile(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbNostrSyncRemoteProfileConstMeta,
        argValues: [path, accountId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbNostrSyncRemoteProfileConstMeta =>
      const TaskConstMeta(
        debugName: "frb_nostr_sync_remote_profile",
        argNames: ["path", "accountId"],
      );

  @override
  Future<String> crateFrbApiFrbRemoveAccount({
    required String path,
    required String accountId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(path);
          var arg1 = cst_encode_String(accountId);
          return wire.wire__crate__frb_api__frb_remove_account(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbRemoveAccountConstMeta,
        argValues: [path, accountId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbRemoveAccountConstMeta =>
      const TaskConstMeta(
        debugName: "frb_remove_account",
        argNames: ["path", "accountId"],
      );

  @override
  Future<void> crateFrbApiFrbRenameMailFolder({
    required String storeUri,
    required String credentialKey,
    required String oldName,
    required String newName,
    required bool useKeychain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(storeUri);
          var arg1 = cst_encode_String(credentialKey);
          var arg2 = cst_encode_String(oldName);
          var arg3 = cst_encode_String(newName);
          var arg4 = cst_encode_bool(useKeychain);
          return wire.wire__crate__frb_api__frb_rename_mail_folder(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbRenameMailFolderConstMeta,
        argValues: [storeUri, credentialKey, oldName, newName, useKeychain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbRenameMailFolderConstMeta =>
      const TaskConstMeta(
        debugName: "frb_rename_mail_folder",
        argNames: [
          "storeUri",
          "credentialKey",
          "oldName",
          "newName",
          "useKeychain",
        ],
      );

  @override
  Future<void> crateFrbApiFrbSaveConfigJson({
    required String path,
    required String configJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(path);
          var arg1 = cst_encode_String(configJson);
          return wire.wire__crate__frb_api__frb_save_config_json(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbSaveConfigJsonConstMeta,
        argValues: [path, configJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbSaveConfigJsonConstMeta =>
      const TaskConstMeta(
        debugName: "frb_save_config_json",
        argNames: ["path", "configJson"],
      );

  @override
  Future<void> crateFrbApiFrbSaveStoreCredential({
    required String credentialId,
    required String storeUri,
    required String username,
    required String password,
    required bool useKeychain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(credentialId);
          var arg1 = cst_encode_String(storeUri);
          var arg2 = cst_encode_String(username);
          var arg3 = cst_encode_String(password);
          var arg4 = cst_encode_bool(useKeychain);
          return wire.wire__crate__frb_api__frb_save_store_credential(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbSaveStoreCredentialConstMeta,
        argValues: [credentialId, storeUri, username, password, useKeychain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbSaveStoreCredentialConstMeta =>
      const TaskConstMeta(
        debugName: "frb_save_store_credential",
        argNames: [
          "credentialId",
          "storeUri",
          "username",
          "password",
          "useKeychain",
        ],
      );

  @override
  Future<void> crateFrbApiFrbSaveTransportCredential({
    required String transportId,
    required String username,
    required String password,
    required bool useKeychain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(transportId);
          var arg1 = cst_encode_String(username);
          var arg2 = cst_encode_String(password);
          var arg3 = cst_encode_bool(useKeychain);
          return wire.wire__crate__frb_api__frb_save_transport_credential(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbSaveTransportCredentialConstMeta,
        argValues: [transportId, username, password, useKeychain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbSaveTransportCredentialConstMeta =>
      const TaskConstMeta(
        debugName: "frb_save_transport_credential",
        argNames: ["transportId", "username", "password", "useKeychain"],
      );

  @override
  Future<void> crateFrbApiFrbSessionCommand({required String commandJson}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(commandJson);
          return wire.wire__crate__frb_api__frb_session_command(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbSessionCommandConstMeta,
        argValues: [commandJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbSessionCommandConstMeta =>
      const TaskConstMeta(
        debugName: "frb_session_command",
        argNames: ["commandJson"],
      );

  @override
  Future<String> crateFrbApiFrbSessionGetFolderMessage({
    required String accountId,
    required String folderName,
    required String messageId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(accountId);
          var arg1 = cst_encode_String(folderName);
          var arg2 = cst_encode_String(messageId);
          return wire.wire__crate__frb_api__frb_session_get_folder_message(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbSessionGetFolderMessageConstMeta,
        argValues: [accountId, folderName, messageId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbSessionGetFolderMessageConstMeta =>
      const TaskConstMeta(
        debugName: "frb_session_get_folder_message",
        argNames: ["accountId", "folderName", "messageId"],
      );

  @override
  Future<String> crateFrbApiFrbSessionListMessagesWindow({
    required String accountId,
    required String folderName,
    required int startIndex,
    required int limit,
    required String messageListSort,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(accountId);
          var arg1 = cst_encode_String(folderName);
          var arg2 = cst_encode_i_32(startIndex);
          var arg3 = cst_encode_i_32(limit);
          var arg4 = cst_encode_String(messageListSort);
          return wire.wire__crate__frb_api__frb_session_list_messages_window(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbSessionListMessagesWindowConstMeta,
        argValues: [accountId, folderName, startIndex, limit, messageListSort],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbSessionListMessagesWindowConstMeta =>
      const TaskConstMeta(
        debugName: "frb_session_list_messages_window",
        argNames: [
          "accountId",
          "folderName",
          "startIndex",
          "limit",
          "messageListSort",
        ],
      );

  @override
  Future<String> crateFrbApiFrbSessionRegisterMailBodyStore({
    required String accountId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(accountId);
          return wire
              .wire__crate__frb_api__frb_session_register_mail_body_store(
                port_,
                arg0,
              );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbSessionRegisterMailBodyStoreConstMeta,
        argValues: [accountId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbSessionRegisterMailBodyStoreConstMeta =>
      const TaskConstMeta(
        debugName: "frb_session_register_mail_body_store",
        argNames: ["accountId"],
      );

  @override
  Stream<String> crateFrbApiFrbSessionStart({required String configXmlPath}) {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            var arg0 = cst_encode_StreamSink_String_Dco(sink);
            var arg1 = cst_encode_String(configXmlPath);
            return wire.wire__crate__frb_api__frb_session_start(
              port_,
              arg0,
              arg1,
            );
          },
          codec: DcoCodec(
            decodeSuccessData: dco_decode_unit,
            decodeErrorData: dco_decode_String,
          ),
          constMeta: kCrateFrbApiFrbSessionStartConstMeta,
          argValues: [sink, configXmlPath],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateFrbApiFrbSessionStartConstMeta => const TaskConstMeta(
    debugName: "frb_session_start",
    argNames: ["sink", "configXmlPath"],
  );

  @override
  Future<String> crateFrbApiFrbTransferMailMessages({
    required String sourceStoreUri,
    required String sourceCredentialKey,
    required String sourceFolder,
    required String destStoreUri,
    required String destCredentialKey,
    required String destFolder,
    required List<String> messageIds,
    required bool isMove,
    required bool useKeychain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(sourceStoreUri);
          var arg1 = cst_encode_String(sourceCredentialKey);
          var arg2 = cst_encode_String(sourceFolder);
          var arg3 = cst_encode_String(destStoreUri);
          var arg4 = cst_encode_String(destCredentialKey);
          var arg5 = cst_encode_String(destFolder);
          var arg6 = cst_encode_list_String(messageIds);
          var arg7 = cst_encode_bool(isMove);
          var arg8 = cst_encode_bool(useKeychain);
          return wire.wire__crate__frb_api__frb_transfer_mail_messages(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
            arg5,
            arg6,
            arg7,
            arg8,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbTransferMailMessagesConstMeta,
        argValues: [
          sourceStoreUri,
          sourceCredentialKey,
          sourceFolder,
          destStoreUri,
          destCredentialKey,
          destFolder,
          messageIds,
          isMove,
          useKeychain,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbTransferMailMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "frb_transfer_mail_messages",
        argNames: [
          "sourceStoreUri",
          "sourceCredentialKey",
          "sourceFolder",
          "destStoreUri",
          "destCredentialKey",
          "destFolder",
          "messageIds",
          "isMove",
          "useKeychain",
        ],
      );

  @override
  Future<String> crateFrbApiFrbUpsertAccount({
    required String path,
    required String accountJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(path);
          var arg1 = cst_encode_String(accountJson);
          return wire.wire__crate__frb_api__frb_upsert_account(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbUpsertAccountConstMeta,
        argValues: [path, accountJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbUpsertAccountConstMeta =>
      const TaskConstMeta(
        debugName: "frb_upsert_account",
        argNames: ["path", "accountJson"],
      );

  @override
  Future<FrbAccount> crateFrbApiFrbJsonParseFrbAccountJson({
    required String input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(input);
          return wire.wire__crate__frb_api__frb_json__parse_frb_account_json(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_frb_account,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbJsonParseFrbAccountJsonConstMeta,
        argValues: [input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbJsonParseFrbAccountJsonConstMeta =>
      const TaskConstMeta(
        debugName: "parse_frb_account_json",
        argNames: ["input"],
      );

  @override
  Future<FrbConfig> crateFrbApiFrbJsonParseFrbConfigJson({
    required String input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(input);
          return wire.wire__crate__frb_api__frb_json__parse_frb_config_json(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_frb_config,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateFrbApiFrbJsonParseFrbConfigJsonConstMeta,
        argValues: [input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbJsonParseFrbConfigJsonConstMeta =>
      const TaskConstMeta(
        debugName: "parse_frb_config_json",
        argNames: ["input"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_string(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  Map<String, List<String>> dco_decode_Map_String_list_String_None(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_list_string(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Dco(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AccountParseState dco_decode_account_parse_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return AccountParseState_Top(
          acc: dco_decode_box_autoadd_frb_account(raw[1]),
          key: dco_decode_opt_String(raw[2]),
          inLegacyTransportIds: dco_decode_bool(raw[3]),
        );
      case 1:
        return AccountParseState_InAttrs(
          acc: dco_decode_box_autoadd_frb_account(raw[1]),
          key: dco_decode_opt_String(raw[2]),
        );
      case 2:
        return AccountParseState_InLists(
          acc: dco_decode_box_autoadd_frb_account(raw[1]),
          listKey: dco_decode_opt_String(raw[2]),
          inArray: dco_decode_bool(raw[3]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AccountParseState dco_decode_box_autoadd_account_parse_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_account_parse_state(raw);
  }

  @protected
  FrbAccount dco_decode_box_autoadd_frb_account(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_frb_account(raw);
  }

  @protected
  FrbConfig dco_decode_box_autoadd_frb_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_frb_config(raw);
  }

  @protected
  FrbTransport dco_decode_box_autoadd_frb_transport(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_frb_transport(raw);
  }

  @protected
  CfgStack dco_decode_cfg_stack(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CfgStack_Root(key: dco_decode_opt_String(raw[1]));
      case 1:
        return CfgStack_InAccountsArray();
      case 2:
        return CfgStack_InAccount(
          dco_decode_box_autoadd_account_parse_state(raw[1]),
        );
      case 3:
        return CfgStack_InTransportsArray();
      case 4:
        return CfgStack_InTransport(
          t: dco_decode_box_autoadd_frb_transport(raw[1]),
          key: dco_decode_opt_String(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  FrbAccount dco_decode_frb_account(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return FrbAccount(
      id: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      backendType: dco_decode_String(arr[2]),
      storeUri: dco_decode_String(arr[3]),
      avatarUrl: dco_decode_opt_String(arr[4]),
      lastFolder: dco_decode_opt_String(arr[5]),
      lastMessageId: dco_decode_opt_String(arr[6]),
      attrs: dco_decode_Map_String_String_None(arr[7]),
      lists: dco_decode_Map_String_list_String_None(arr[8]),
    );
  }

  @protected
  FrbConfig dco_decode_frb_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return FrbConfig(
      accounts: dco_decode_list_frb_account(arr[0]),
      transports: dco_decode_list_frb_transport(arr[1]),
      selectedStoreId: dco_decode_opt_String(arr[2]),
      dateFormat: dco_decode_String(arr[3]),
      resourcePolicy: dco_decode_String(arr[4]),
      useKeychain: dco_decode_bool(arr[5]),
      loadRemoteImages: dco_decode_bool(arr[6]),
      threadedView: dco_decode_bool(arr[7]),
      quoteOriginal: dco_decode_bool(arr[8]),
      deleteMode: dco_decode_String(arr[9]),
      trashFolderName: dco_decode_String(arr[10]),
      messageListSort: dco_decode_String(arr[11]),
      notifyNewMessages: dco_decode_bool(arr[12]),
    );
  }

  @protected
  FrbConfigParse dco_decode_frb_config_parse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FrbConfigParse(
      config: dco_decode_frb_config(arr[0]),
      stack: dco_decode_list_cfg_stack(arr[1]),
      err: dco_decode_opt_String(arr[2]),
      jsonLegacyRootFolder: dco_decode_opt_String(arr[3]),
      jsonLegacyRootMessageId: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  FrbTransport dco_decode_frb_transport(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return FrbTransport(
      id: dco_decode_String(arr[0]),
      transportType: dco_decode_String(arr[1]),
      displayName: dco_decode_String(arr[2]),
      host: dco_decode_String(arr[3]),
      port: dco_decode_u_16(arr[4]),
      security: dco_decode_String(arr[5]),
      transportUri: dco_decode_String(arr[6]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CfgStack> dco_decode_list_cfg_stack(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_cfg_stack).toList();
  }

  @protected
  List<FrbAccount> dco_decode_list_frb_account(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_frb_account).toList();
  }

  @protected
  List<FrbTransport> dco_decode_list_frb_transport(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_frb_transport).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, List<String>)> dco_decode_list_record_string_list_string(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_string_list_string)
        .toList();
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  (String, List<String>) dco_decode_record_string_list_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_list_String(arr[1]));
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  Map<String, List<String>> sse_decode_Map_String_list_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_list_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Dco(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AccountParseState sse_decode_account_parse_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_acc = sse_decode_box_autoadd_frb_account(deserializer);
        var var_key = sse_decode_opt_String(deserializer);
        var var_inLegacyTransportIds = sse_decode_bool(deserializer);
        return AccountParseState_Top(
          acc: var_acc,
          key: var_key,
          inLegacyTransportIds: var_inLegacyTransportIds,
        );
      case 1:
        var var_acc = sse_decode_box_autoadd_frb_account(deserializer);
        var var_key = sse_decode_opt_String(deserializer);
        return AccountParseState_InAttrs(acc: var_acc, key: var_key);
      case 2:
        var var_acc = sse_decode_box_autoadd_frb_account(deserializer);
        var var_listKey = sse_decode_opt_String(deserializer);
        var var_inArray = sse_decode_bool(deserializer);
        return AccountParseState_InLists(
          acc: var_acc,
          listKey: var_listKey,
          inArray: var_inArray,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AccountParseState sse_decode_box_autoadd_account_parse_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_account_parse_state(deserializer));
  }

  @protected
  FrbAccount sse_decode_box_autoadd_frb_account(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_frb_account(deserializer));
  }

  @protected
  FrbConfig sse_decode_box_autoadd_frb_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_frb_config(deserializer));
  }

  @protected
  FrbTransport sse_decode_box_autoadd_frb_transport(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_frb_transport(deserializer));
  }

  @protected
  CfgStack sse_decode_cfg_stack(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_key = sse_decode_opt_String(deserializer);
        return CfgStack_Root(key: var_key);
      case 1:
        return CfgStack_InAccountsArray();
      case 2:
        var var_field0 = sse_decode_box_autoadd_account_parse_state(
          deserializer,
        );
        return CfgStack_InAccount(var_field0);
      case 3:
        return CfgStack_InTransportsArray();
      case 4:
        var var_t = sse_decode_box_autoadd_frb_transport(deserializer);
        var var_key = sse_decode_opt_String(deserializer);
        return CfgStack_InTransport(t: var_t, key: var_key);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  FrbAccount sse_decode_frb_account(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_backendType = sse_decode_String(deserializer);
    var var_storeUri = sse_decode_String(deserializer);
    var var_avatarUrl = sse_decode_opt_String(deserializer);
    var var_lastFolder = sse_decode_opt_String(deserializer);
    var var_lastMessageId = sse_decode_opt_String(deserializer);
    var var_attrs = sse_decode_Map_String_String_None(deserializer);
    var var_lists = sse_decode_Map_String_list_String_None(deserializer);
    return FrbAccount(
      id: var_id,
      label: var_label,
      backendType: var_backendType,
      storeUri: var_storeUri,
      avatarUrl: var_avatarUrl,
      lastFolder: var_lastFolder,
      lastMessageId: var_lastMessageId,
      attrs: var_attrs,
      lists: var_lists,
    );
  }

  @protected
  FrbConfig sse_decode_frb_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_accounts = sse_decode_list_frb_account(deserializer);
    var var_transports = sse_decode_list_frb_transport(deserializer);
    var var_selectedStoreId = sse_decode_opt_String(deserializer);
    var var_dateFormat = sse_decode_String(deserializer);
    var var_resourcePolicy = sse_decode_String(deserializer);
    var var_useKeychain = sse_decode_bool(deserializer);
    var var_loadRemoteImages = sse_decode_bool(deserializer);
    var var_threadedView = sse_decode_bool(deserializer);
    var var_quoteOriginal = sse_decode_bool(deserializer);
    var var_deleteMode = sse_decode_String(deserializer);
    var var_trashFolderName = sse_decode_String(deserializer);
    var var_messageListSort = sse_decode_String(deserializer);
    var var_notifyNewMessages = sse_decode_bool(deserializer);
    return FrbConfig(
      accounts: var_accounts,
      transports: var_transports,
      selectedStoreId: var_selectedStoreId,
      dateFormat: var_dateFormat,
      resourcePolicy: var_resourcePolicy,
      useKeychain: var_useKeychain,
      loadRemoteImages: var_loadRemoteImages,
      threadedView: var_threadedView,
      quoteOriginal: var_quoteOriginal,
      deleteMode: var_deleteMode,
      trashFolderName: var_trashFolderName,
      messageListSort: var_messageListSort,
      notifyNewMessages: var_notifyNewMessages,
    );
  }

  @protected
  FrbConfigParse sse_decode_frb_config_parse(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_config = sse_decode_frb_config(deserializer);
    var var_stack = sse_decode_list_cfg_stack(deserializer);
    var var_err = sse_decode_opt_String(deserializer);
    var var_jsonLegacyRootFolder = sse_decode_opt_String(deserializer);
    var var_jsonLegacyRootMessageId = sse_decode_opt_String(deserializer);
    return FrbConfigParse(
      config: var_config,
      stack: var_stack,
      err: var_err,
      jsonLegacyRootFolder: var_jsonLegacyRootFolder,
      jsonLegacyRootMessageId: var_jsonLegacyRootMessageId,
    );
  }

  @protected
  FrbTransport sse_decode_frb_transport(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_transportType = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_security = sse_decode_String(deserializer);
    var var_transportUri = sse_decode_String(deserializer);
    return FrbTransport(
      id: var_id,
      transportType: var_transportType,
      displayName: var_displayName,
      host: var_host,
      port: var_port,
      security: var_security,
      transportUri: var_transportUri,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CfgStack> sse_decode_list_cfg_stack(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CfgStack>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_cfg_stack(deserializer));
    }
    return ans_;
  }

  @protected
  List<FrbAccount> sse_decode_list_frb_account(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FrbAccount>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_frb_account(deserializer));
    }
    return ans_;
  }

  @protected
  List<FrbTransport> sse_decode_list_frb_transport(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FrbTransport>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_frb_transport(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, List<String>)> sse_decode_list_record_string_list_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, List<String>)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_list_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, List<String>) sse_decode_record_string_list_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_list_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_16(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_Map_String_list_String_None(
    Map<String, List<String>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_list_string(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_String_Dco(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_account_parse_state(
    AccountParseState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case AccountParseState_Top(
        acc: final acc,
        key: final key,
        inLegacyTransportIds: final inLegacyTransportIds,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_frb_account(acc, serializer);
        sse_encode_opt_String(key, serializer);
        sse_encode_bool(inLegacyTransportIds, serializer);
      case AccountParseState_InAttrs(acc: final acc, key: final key):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_frb_account(acc, serializer);
        sse_encode_opt_String(key, serializer);
      case AccountParseState_InLists(
        acc: final acc,
        listKey: final listKey,
        inArray: final inArray,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_box_autoadd_frb_account(acc, serializer);
        sse_encode_opt_String(listKey, serializer);
        sse_encode_bool(inArray, serializer);
    }
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_account_parse_state(
    AccountParseState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_account_parse_state(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_frb_account(
    FrbAccount self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_frb_account(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_frb_config(
    FrbConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_frb_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_frb_transport(
    FrbTransport self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_frb_transport(self, serializer);
  }

  @protected
  void sse_encode_cfg_stack(CfgStack self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CfgStack_Root(key: final key):
        sse_encode_i_32(0, serializer);
        sse_encode_opt_String(key, serializer);
      case CfgStack_InAccountsArray():
        sse_encode_i_32(1, serializer);
      case CfgStack_InAccount(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_box_autoadd_account_parse_state(field0, serializer);
      case CfgStack_InTransportsArray():
        sse_encode_i_32(3, serializer);
      case CfgStack_InTransport(t: final t, key: final key):
        sse_encode_i_32(4, serializer);
        sse_encode_box_autoadd_frb_transport(t, serializer);
        sse_encode_opt_String(key, serializer);
    }
  }

  @protected
  void sse_encode_frb_account(FrbAccount self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.backendType, serializer);
    sse_encode_String(self.storeUri, serializer);
    sse_encode_opt_String(self.avatarUrl, serializer);
    sse_encode_opt_String(self.lastFolder, serializer);
    sse_encode_opt_String(self.lastMessageId, serializer);
    sse_encode_Map_String_String_None(self.attrs, serializer);
    sse_encode_Map_String_list_String_None(self.lists, serializer);
  }

  @protected
  void sse_encode_frb_config(FrbConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_frb_account(self.accounts, serializer);
    sse_encode_list_frb_transport(self.transports, serializer);
    sse_encode_opt_String(self.selectedStoreId, serializer);
    sse_encode_String(self.dateFormat, serializer);
    sse_encode_String(self.resourcePolicy, serializer);
    sse_encode_bool(self.useKeychain, serializer);
    sse_encode_bool(self.loadRemoteImages, serializer);
    sse_encode_bool(self.threadedView, serializer);
    sse_encode_bool(self.quoteOriginal, serializer);
    sse_encode_String(self.deleteMode, serializer);
    sse_encode_String(self.trashFolderName, serializer);
    sse_encode_String(self.messageListSort, serializer);
    sse_encode_bool(self.notifyNewMessages, serializer);
  }

  @protected
  void sse_encode_frb_config_parse(
    FrbConfigParse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_frb_config(self.config, serializer);
    sse_encode_list_cfg_stack(self.stack, serializer);
    sse_encode_opt_String(self.err, serializer);
    sse_encode_opt_String(self.jsonLegacyRootFolder, serializer);
    sse_encode_opt_String(self.jsonLegacyRootMessageId, serializer);
  }

  @protected
  void sse_encode_frb_transport(FrbTransport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.transportType, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.security, serializer);
    sse_encode_String(self.transportUri, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_cfg_stack(
    List<CfgStack> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_cfg_stack(item, serializer);
    }
  }

  @protected
  void sse_encode_list_frb_account(
    List<FrbAccount> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_frb_account(item, serializer);
    }
  }

  @protected
  void sse_encode_list_frb_transport(
    List<FrbTransport> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_frb_transport(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_list_string(
    List<(String, List<String>)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_list_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_list_string(
    (String, List<String>) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_list_String(self.$2, serializer);
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
