// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `config_path_for_relay_lookup`, `config_xml_path`, `default_message_list_sort`, `email_from_google_id_token_jwt`, `load_frb_config_struct`, `mail_body_path_message_id_segment`, `merge_accounts_from_tagliacarte_xml`, `persist_frb_config`, `read_config`, `register_primary_config_xml_path`, `resolve_mail_account`, `resolve_transport_in_primary_config`, `validate_frb_config_for_save`, `write_config`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

Future<String> frbLoadConfigJson({required String path}) =>
    RustLib.instance.api.crateFrbApiFrbLoadConfigJson(path: path);

Future<void> frbSaveConfigJson({
  required String path,
  required String configJson,
}) => RustLib.instance.api.crateFrbApiFrbSaveConfigJson(
  path: path,
  configJson: configJson,
);

Future<String> frbUpsertAccount({
  required String path,
  required String accountJson,
}) => RustLib.instance.api.crateFrbApiFrbUpsertAccount(
  path: path,
  accountJson: accountJson,
);

Future<String> frbRemoveAccount({
  required String path,
  required String accountId,
}) => RustLib.instance.api.crateFrbApiFrbRemoveAccount(
  path: path,
  accountId: accountId,
);

Future<String> frbListMailFolders({required String accountId}) =>
    RustLib.instance.api.crateFrbApiFrbListMailFolders(accountId: accountId);

Future<String> frbNntpListActiveWildmat({
  required String accountId,
  required String wildmat,
}) => RustLib.instance.api.crateFrbApiFrbNntpListActiveWildmat(
  accountId: accountId,
  wildmat: wildmat,
);

Future<void> frbImapSubscribeMailbox({
  required String accountId,
  required String mailbox,
}) => RustLib.instance.api.crateFrbApiFrbImapSubscribeMailbox(
  accountId: accountId,
  mailbox: mailbox,
);

Future<void> frbImapUnsubscribeMailbox({
  required String accountId,
  required String mailbox,
}) => RustLib.instance.api.crateFrbApiFrbImapUnsubscribeMailbox(
  accountId: accountId,
  mailbox: mailbox,
);

Future<void> frbNntpSetGroupSubscribed({
  required String accountId,
  required String group,
  required bool subscribed,
}) => RustLib.instance.api.crateFrbApiFrbNntpSetGroupSubscribed(
  accountId: accountId,
  group: group,
  subscribed: subscribed,
);

Future<void> frbMatrixJoinRoom({
  required String accountId,
  required String roomIdOrAlias,
}) => RustLib.instance.api.crateFrbApiFrbMatrixJoinRoom(
  accountId: accountId,
  roomIdOrAlias: roomIdOrAlias,
);

Future<void> frbMatrixLeaveRoom({
  required String accountId,
  required String roomId,
}) => RustLib.instance.api.crateFrbApiFrbMatrixLeaveRoom(
  accountId: accountId,
  roomId: roomId,
);

Future<bool> frbImapTakeFolderListStale({required String accountId}) => RustLib
    .instance
    .api
    .crateFrbApiFrbImapTakeFolderListStale(accountId: accountId);

Future<void> frbImapConfigureIdleThreshold({
  required String accountId,
  required int minIdleSeconds,
}) => RustLib.instance.api.crateFrbApiFrbImapConfigureIdleThreshold(
  accountId: accountId,
  minIdleSeconds: minIdleSeconds,
);

Future<void> frbCreateMailFolder({
  required String accountId,
  required String folderPath,
}) => RustLib.instance.api.crateFrbApiFrbCreateMailFolder(
  accountId: accountId,
  folderPath: folderPath,
);

Future<void> frbRenameMailFolder({
  required String accountId,
  required String oldName,
  required String newName,
}) => RustLib.instance.api.crateFrbApiFrbRenameMailFolder(
  accountId: accountId,
  oldName: oldName,
  newName: newName,
);

Future<void> frbDeleteMailFolder({
  required String accountId,
  required String folderName,
}) => RustLib.instance.api.crateFrbApiFrbDeleteMailFolder(
  accountId: accountId,
  folderName: folderName,
);

Future<String> frbListFolderMessages({
  required String accountId,
  required String folderName,
  required int skip,
  required int limit,
}) => RustLib.instance.api.crateFrbApiFrbListFolderMessages(
  accountId: accountId,
  folderName: folderName,
  skip: skip,
  limit: limit,
);

/// List one page of message summaries in **ascending** order for [message_list_sort]. JSON includes
/// `total`, `startIndex`, `messages`, `listStrategy` (`imapSort` or `fullScan`).
Future<String> frbListFolderMessagesWindow({
  required String accountId,
  required String folderName,
  required int startIndex,
  required int limit,
  required String messageListSort,
}) => RustLib.instance.api.crateFrbApiFrbListFolderMessagesWindow(
  accountId: accountId,
  folderName: folderName,
  startIndex: startIndex,
  limit: limit,
  messageListSort: messageListSort,
);

Future<String> frbGetFolderMessage({
  required String accountId,
  required String folderName,
  required String messageId,
}) => RustLib.instance.api.crateFrbApiFrbGetFolderMessage(
  accountId: accountId,
  folderName: folderName,
  messageId: messageId,
);

Future<void> frbMarkFolderMessageRead({
  required String accountId,
  required String folderName,
  required String messageId,
}) => RustLib.instance.api.crateFrbApiFrbMarkFolderMessageRead(
  accountId: accountId,
  folderName: folderName,
  messageId: messageId,
);

/// JSON: `{ results: [{ id, ok, error? }], okCount, failedCount }`. Cross-store move deletes source only after successful append.
Future<String> frbTransferMailMessages({
  required String sourceAccountId,
  required String sourceFolder,
  required String destAccountId,
  required String destFolder,
  required List<String> messageIds,
  required bool isMove,
}) => RustLib.instance.api.crateFrbApiFrbTransferMailMessages(
  sourceAccountId: sourceAccountId,
  sourceFolder: sourceFolder,
  destAccountId: destAccountId,
  destFolder: destFolder,
  messageIds: messageIds,
  isMove: isMove,
);

/// JSON: `{ results: [{ id, ok, error? }], okCount, failedCount }`. IMAP uses per-account delete mode and trash folder.
Future<String> frbDeleteMailMessages({
  required String accountId,
  required String folderName,
  required List<String> messageIds,
}) => RustLib.instance.api.crateFrbApiFrbDeleteMailMessages(
  accountId: accountId,
  folderName: folderName,
  messageIds: messageIds,
);

Future<void> frbExpungeMailFolder({
  required String accountId,
  required String folderName,
}) => RustLib.instance.api.crateFrbApiFrbExpungeMailFolder(
  accountId: accountId,
  folderName: folderName,
);

/// Set whether the mail-body HTTPS server requires a **client certificate** (mutual TLS).
/// Default is **true** (strict). Call with **false** before [`frb_mail_body_server_init`] when the
/// embedded WebView cannot present [`client_cert_pem`] yet (loopback TLS remains enabled).
Future<void> frbMailBodySetTlsRequireClientCert({required bool require}) =>
    RustLib.instance.api.crateFrbApiFrbMailBodySetTlsRequireClientCert(
      require: require,
    );

/// Fetch one IMAP MIME part by section (decoded). JSON: `{ "bytesBase64": "..." }`.
/// Start loopback mTLS server if needed. JSON includes `enforcesClientCert`, PEM material, `baseUrl`.
Future<String> frbMailBodyServerInit() =>
    RustLib.instance.api.crateFrbApiFrbMailBodyServerInit();

/// Register store for `/view/{key}/...` URLs. Call after `frb_mail_body_server_init`. Returns opaque `storeKey`.
Future<String> frbMailBodyRegisterStore({required String accountId}) => RustLib
    .instance
    .api
    .crateFrbApiFrbMailBodyRegisterStore(accountId: accountId);

/// Build message body URL. `message_id` is IMAP UID as decimal digits, or any store-specific id (percent-encoded in path).
/// `folder_name` is raw mailbox name; `extra_query` like `fg=fff&bg=000`.
Future<String> frbMailBodyMessageUrl({
  required String storeKey,
  required String folderName,
  required String messageId,
  required String extraQuery,
}) => RustLib.instance.api.crateFrbApiFrbMailBodyMessageUrl(
  storeKey: storeKey,
  folderName: folderName,
  messageId: messageId,
  extraQuery: extraQuery,
);

Future<String> frbFetchFolderMessagePart({
  required String accountId,
  required String folderName,
  required String messageId,
  required String imapSection,
  required String transferEncoding,
}) => RustLib.instance.api.crateFrbApiFrbFetchFolderMessagePart(
  accountId: accountId,
  folderName: folderName,
  messageId: messageId,
  imapSection: imapSection,
  transferEncoding: transferEncoding,
);

/// Persists secrets for the store identified by `account_id` (XML `<store id="…">`). Invalidates IMAP cache.
///
/// If the account row is not in config yet (e.g. Nostr identity wizard before first save), writes the vault
/// entry keyed by `account_id` only — no store cache invalidation until the store exists in XML.
Future<void> frbSaveStoreCredential({
  required String accountId,
  required String username,
  required String password,
}) => RustLib.instance.api.crateFrbApiFrbSaveStoreCredential(
  accountId: accountId,
  username: username,
  password: password,
);

/// Whether the credential vault has a non-empty password or token for this `<store id="…">`.
///
/// Used after saving a new account (e.g. Matrix) so the UI can open sign-in when the vault is
/// still empty, without relying on parsing sync/list error strings.
Future<bool> frbStoreHasSavedPassword({required String accountId}) => RustLib
    .instance
    .api
    .crateFrbApiFrbStoreHasSavedPassword(accountId: accountId);

/// Outbound transport credentials (e.g. SMTP), keyed by transport id (`t1`). Keychain vs file
/// follows [FrbConfig::use_keychain] from the active config (same as store credentials).
Future<void> frbSaveTransportCredential({
  required String transportId,
  required String username,
  required String password,
}) => RustLib.instance.api.crateFrbApiFrbSaveTransportCredential(
  transportId: transportId,
  username: username,
  password: password,
);

/// Send one message via SMTP using the transport row identified by `transport_id` (not URI).
/// [compose_json] is camelCase: `from`, `to`, `cc`, `bcc`, `subject`, `bodyPlain`, optional `bodyHtml`.
Future<void> frbSendSmtpMessage({
  required String transportId,
  required String composeJson,
}) => RustLib.instance.api.crateFrbApiFrbSendSmtpMessage(
  transportId: transportId,
  composeJson: composeJson,
);

/// Connect to SMTP, authenticate with saved credentials, QUIT (no mail).
Future<void> frbVerifySmtpTransport({required String transportId}) => RustLib
    .instance
    .api
    .crateFrbApiFrbVerifySmtpTransport(transportId: transportId);

/// POST a Netnews article using the NNTP store account (`<store type="nntp">`), same server connection as reading.
/// [compose_json] is camelCase: `from`, `newsgroups` (array of strings), `subject`, `bodyPlain`, optional `attachments`,
/// optional `inReplyTo`, optional `references`.
Future<void> frbSendNntpMessage({
  required String storeAccountId,
  required String composeJson,
}) => RustLib.instance.api.crateFrbApiFrbSendNntpMessage(
  storeAccountId: storeAccountId,
  composeJson: composeJson,
);

Future<String> frbNostrGenerateKeypairJson() =>
    RustLib.instance.api.crateFrbApiFrbNostrGenerateKeypairJson();

Future<String> frbNostrGetPublicKeyFromSecret({required String secret}) =>
    RustLib.instance.api.crateFrbApiFrbNostrGetPublicKeyFromSecret(
      secret: secret,
    );

Future<String> frbNostrHexToNpub({required String hexPubkey}) =>
    RustLib.instance.api.crateFrbApiFrbNostrHexToNpub(hexPubkey: hexPubkey);

Future<String> frbNostrSecretKeyToHex({required String input}) =>
    RustLib.instance.api.crateFrbApiFrbNostrSecretKeyToHex(input: input);

/// Publish kind 0 metadata from current account fields (needs nsec in vault).
Future<void> frbNostrPublishProfile({
  required String path,
  required String accountId,
}) => RustLib.instance.api.crateFrbApiFrbNostrPublishProfile(
  path: path,
  accountId: accountId,
);

/// Fetch profile + NIP-65 relay list and merge into config (background use).
Future<void> frbNostrSyncRemoteProfile({
  required String path,
  required String accountId,
}) => RustLib.instance.api.crateFrbApiFrbNostrSyncRemoteProfile(
  path: path,
  accountId: accountId,
);

/// Subscribe to app-level mail events (folder lists, connection status, command results).
/// Call once after [RustLib.init]. [config_xml_path] is the same `config.xml` path Flutter uses.
Stream<String> frbSessionStart({required String configXmlPath}) => RustLib
    .instance
    .api
    .crateFrbApiFrbSessionStart(configXmlPath: configXmlPath);

/// Register new `<store>` accounts with the running session (spawn folder loops) after Flutter saves config.
Future<void> frbSessionReloadAccounts({required String configXmlPath}) =>
    RustLib.instance.api.crateFrbApiFrbSessionReloadAccounts(
      configXmlPath: configXmlPath,
    );

/// Browser-based Google OAuth (PKCE); saves refreshable token JSON for the Gmail store vault key.
Future<void> frbGmailOauthSignIn({required String accountId}) =>
    RustLib.instance.api.crateFrbApiFrbGmailOauthSignIn(accountId: accountId);

/// Fire-and-forget session command (JSON with `type`: markRead, refreshFolders, transferMessages).
Future<void> frbSessionCommand({required String commandJson}) =>
    RustLib.instance.api.crateFrbApiFrbSessionCommand(commandJson: commandJson);

/// Paged message summaries for [account_id]; session maps to store URI and vault key.
Future<String> frbSessionListMessagesWindow({
  required String accountId,
  required String folderName,
  required int startIndex,
  required int limit,
  required String messageListSort,
}) => RustLib.instance.api.crateFrbApiFrbSessionListMessagesWindow(
  accountId: accountId,
  folderName: folderName,
  startIndex: startIndex,
  limit: limit,
  messageListSort: messageListSort,
);

/// Full message JSON for [account_id] (same shape as [frb_get_folder_message]).
Future<String> frbSessionGetFolderMessage({
  required String accountId,
  required String folderName,
  required String messageId,
}) => RustLib.instance.api.crateFrbApiFrbSessionGetFolderMessage(
  accountId: accountId,
  folderName: folderName,
  messageId: messageId,
);

/// Register store for mail-body HTTPS URLs; returns opaque key (after [frb_mail_body_server_init]).
Future<String> frbSessionRegisterMailBodyStore({required String accountId}) =>
    RustLib.instance.api.crateFrbApiFrbSessionRegisterMailBodyStore(
      accountId: accountId,
    );

class FrbAccount {
  final String id;
  final String label;
  final String backendType;
  final String? avatarUrl;
  final String? lastFolder;
  final String? lastMessageId;

  /// Backend-specific scalar settings (IMAP host/port, Nostr npub/nip05, Maildir path, …).
  final Map<String, String> attrs;

  /// Backend-specific lists (`transportIds`, `relayUrls`, …).
  final Map<String, List<String>> lists;

  const FrbAccount({
    required this.id,
    required this.label,
    required this.backendType,
    this.avatarUrl,
    this.lastFolder,
    this.lastMessageId,
    required this.attrs,
    required this.lists,
  });

  static Future<FrbAccount> default_() =>
      RustLib.instance.api.crateFrbApiFrbAccountDefault();

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      backendType.hashCode ^
      avatarUrl.hashCode ^
      lastFolder.hashCode ^
      lastMessageId.hashCode ^
      attrs.hashCode ^
      lists.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbAccount &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          backendType == other.backendType &&
          avatarUrl == other.avatarUrl &&
          lastFolder == other.lastFolder &&
          lastMessageId == other.lastMessageId &&
          attrs == other.attrs &&
          lists == other.lists;
}

class FrbConfig {
  final List<FrbAccount> accounts;
  final List<FrbTransport> transports;
  final String? selectedStoreId;
  final String dateFormat;
  final String resourcePolicy;
  final bool useKeychain;
  final bool loadRemoteImages;
  final bool threadedView;
  final bool quoteOriginal;

  /// Line shown before quoted text; placeholders: `$date`, `$time`, `$sender`.
  final String replyHeaderTemplate;

  /// ICU date pattern; empty = device locale long date (handled in Flutter).
  final String replyDateFormat;

  /// ICU time pattern; empty = device locale short time (handled in Flutter).
  final String replyTimeFormat;

  /// Prepended to each line of quoted original body (e.g. `"> "`).
  final String replyLinePrefix;

  /// `plain` or `html_smtp` (preserve original HTML in outgoing multipart for SMTP only).
  final String replyQuoteMode;

  /// Rich compose: order of new text vs quoted block in generated `text/plain` (`before_quote` | `after_quote`).
  final String replyPlainPosition;

  /// Symbolic message list sort, e.g. `date_desc`, `from_asc`, `subject_asc`.
  final String messageListSort;

  /// In-app / OS new-mail notifications (toasts, local notifications).
  final bool notifyNewMessages;

  /// Use Quill rich body on the email compose screen (non-NNTP).
  final bool composeUseRichText;

  /// Use Quill in Matrix conversation composer when supported.
  final bool matrixChatUseRichText;

  const FrbConfig({
    required this.accounts,
    required this.transports,
    this.selectedStoreId,
    required this.dateFormat,
    required this.resourcePolicy,
    required this.useKeychain,
    required this.loadRemoteImages,
    required this.threadedView,
    required this.quoteOriginal,
    required this.replyHeaderTemplate,
    required this.replyDateFormat,
    required this.replyTimeFormat,
    required this.replyLinePrefix,
    required this.replyQuoteMode,
    required this.replyPlainPosition,
    required this.messageListSort,
    required this.notifyNewMessages,
    required this.composeUseRichText,
    required this.matrixChatUseRichText,
  });

  static Future<FrbConfig> default_() =>
      RustLib.instance.api.crateFrbApiFrbConfigDefault();

  @override
  int get hashCode =>
      accounts.hashCode ^
      transports.hashCode ^
      selectedStoreId.hashCode ^
      dateFormat.hashCode ^
      resourcePolicy.hashCode ^
      useKeychain.hashCode ^
      loadRemoteImages.hashCode ^
      threadedView.hashCode ^
      quoteOriginal.hashCode ^
      replyHeaderTemplate.hashCode ^
      replyDateFormat.hashCode ^
      replyTimeFormat.hashCode ^
      replyLinePrefix.hashCode ^
      replyQuoteMode.hashCode ^
      replyPlainPosition.hashCode ^
      messageListSort.hashCode ^
      notifyNewMessages.hashCode ^
      composeUseRichText.hashCode ^
      matrixChatUseRichText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbConfig &&
          runtimeType == other.runtimeType &&
          accounts == other.accounts &&
          transports == other.transports &&
          selectedStoreId == other.selectedStoreId &&
          dateFormat == other.dateFormat &&
          resourcePolicy == other.resourcePolicy &&
          useKeychain == other.useKeychain &&
          loadRemoteImages == other.loadRemoteImages &&
          threadedView == other.threadedView &&
          quoteOriginal == other.quoteOriginal &&
          replyHeaderTemplate == other.replyHeaderTemplate &&
          replyDateFormat == other.replyDateFormat &&
          replyTimeFormat == other.replyTimeFormat &&
          replyLinePrefix == other.replyLinePrefix &&
          replyQuoteMode == other.replyQuoteMode &&
          replyPlainPosition == other.replyPlainPosition &&
          messageListSort == other.messageListSort &&
          notifyNewMessages == other.notifyNewMessages &&
          composeUseRichText == other.composeUseRichText &&
          matrixChatUseRichText == other.matrixChatUseRichText;
}

class FrbTransport {
  final String id;
  final String transportType;
  final String displayName;
  final String host;
  final int port;
  final String security;
  final String defaultFrom;
  final String dsnNotify;

  const FrbTransport({
    required this.id,
    required this.transportType,
    required this.displayName,
    required this.host,
    required this.port,
    required this.security,
    required this.defaultFrom,
    required this.dsnNotify,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      transportType.hashCode ^
      displayName.hashCode ^
      host.hashCode ^
      port.hashCode ^
      security.hashCode ^
      defaultFrom.hashCode ^
      dsnNotify.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbTransport &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          transportType == other.transportType &&
          displayName == other.displayName &&
          host == other.host &&
          port == other.port &&
          security == other.security &&
          defaultFrom == other.defaultFrom &&
          dsnNotify == other.dsnNotify;
}
