// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';
import 'frb_api.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  FrbAccount dco_decode_frb_account(dynamic raw);

  @protected
  FrbConfig dco_decode_frb_config(dynamic raw);

  @protected
  FrbTransport dco_decode_frb_transport(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FrbAccount> dco_decode_list_frb_account(dynamic raw);

  @protected
  List<FrbTransport> dco_decode_list_frb_transport(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  FrbAccount sse_decode_frb_account(SseDeserializer deserializer);

  @protected
  FrbConfig sse_decode_frb_config(SseDeserializer deserializer);

  @protected
  FrbTransport sse_decode_frb_transport(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FrbAccount> sse_decode_list_frb_account(SseDeserializer deserializer);

  @protected
  List<FrbTransport> sse_decode_list_frb_transport(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_box_autoadd_u_16(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_u_16(raw);
  }

  @protected
  JSAny cst_encode_frb_account(FrbAccount raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.label),
      cst_encode_String(raw.backendType),
      cst_encode_String(raw.storeUri),
      cst_encode_list_String(raw.transportIds),
      cst_encode_opt_String(raw.transportUri),
      cst_encode_opt_String(raw.username),
      cst_encode_opt_String(raw.host),
      cst_encode_opt_box_autoadd_u_16(raw.port),
      cst_encode_opt_String(raw.security),
      cst_encode_opt_String(raw.path),
      cst_encode_opt_String(raw.email),
      cst_encode_opt_String(raw.avatarUrl),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_frb_config(FrbConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_frb_account(raw.accounts),
      cst_encode_list_frb_transport(raw.transports),
      cst_encode_opt_String(raw.selectedStoreId),
      cst_encode_String(raw.dateFormat),
      cst_encode_String(raw.resourcePolicy),
      cst_encode_bool(raw.useKeychain),
      cst_encode_bool(raw.loadRemoteImages),
      cst_encode_bool(raw.threadedView),
      cst_encode_bool(raw.quoteOriginal),
      cst_encode_String(raw.deleteMode),
      cst_encode_String(raw.trashFolderName),
      cst_encode_String(raw.messageListSort),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_frb_transport(FrbTransport raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.transportType),
      cst_encode_String(raw.displayName),
      cst_encode_String(raw.host),
      cst_encode_u_16(raw.port),
      cst_encode_String(raw.security),
      cst_encode_String(raw.transportUri),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_String).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_frb_account(List<FrbAccount> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_frb_account).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_frb_transport(List<FrbTransport> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_frb_transport).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  String? cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_String(raw);
  }

  @protected
  int? cst_encode_opt_box_autoadd_u_16(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_u_16(raw);
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_u_16(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_frb_account(FrbAccount self, SseSerializer serializer);

  @protected
  void sse_encode_frb_config(FrbConfig self, SseSerializer serializer);

  @protected
  void sse_encode_frb_transport(FrbTransport self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_frb_account(
    List<FrbAccount> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_transport(
    List<FrbTransport> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__frb_api__frb_account_default(NativePortType port_) =>
      wasmModule.wire__crate__frb_api__frb_account_default(port_);

  void wire__crate__frb_api__frb_config_default(NativePortType port_) =>
      wasmModule.wire__crate__frb_api__frb_config_default(port_);

  void wire__crate__frb_api__frb_create_mail_folder(
    NativePortType port_,
    String store_uri,
    String credential_key,
    String folder_path,
    bool use_keychain,
  ) => wasmModule.wire__crate__frb_api__frb_create_mail_folder(
    port_,
    store_uri,
    credential_key,
    folder_path,
    use_keychain,
  );

  void wire__crate__frb_api__frb_delete_mail_folder(
    NativePortType port_,
    String store_uri,
    String credential_key,
    String folder_name,
    bool use_keychain,
  ) => wasmModule.wire__crate__frb_api__frb_delete_mail_folder(
    port_,
    store_uri,
    credential_key,
    folder_name,
    use_keychain,
  );

  void wire__crate__frb_api__frb_expunge_mail_folder(
    NativePortType port_,
    String store_uri,
    String credential_key,
    String folder_name,
    bool use_keychain,
  ) => wasmModule.wire__crate__frb_api__frb_expunge_mail_folder(
    port_,
    store_uri,
    credential_key,
    folder_name,
    use_keychain,
  );

  void wire__crate__frb_api__frb_fetch_folder_message_part(
    NativePortType port_,
    String store_uri,
    String credential_key,
    String folder_name,
    String message_id,
    String imap_section,
    String transfer_encoding,
    bool use_keychain,
  ) => wasmModule.wire__crate__frb_api__frb_fetch_folder_message_part(
    port_,
    store_uri,
    credential_key,
    folder_name,
    message_id,
    imap_section,
    transfer_encoding,
    use_keychain,
  );

  void wire__crate__frb_api__frb_get_folder_message(
    NativePortType port_,
    String store_uri,
    String credential_key,
    String folder_name,
    String message_id,
    bool use_keychain,
  ) => wasmModule.wire__crate__frb_api__frb_get_folder_message(
    port_,
    store_uri,
    credential_key,
    folder_name,
    message_id,
    use_keychain,
  );

  void wire__crate__frb_api__frb_list_folder_messages(
    NativePortType port_,
    String store_uri,
    String credential_key,
    String folder_name,
    int skip,
    int limit,
    bool use_keychain,
  ) => wasmModule.wire__crate__frb_api__frb_list_folder_messages(
    port_,
    store_uri,
    credential_key,
    folder_name,
    skip,
    limit,
    use_keychain,
  );

  void wire__crate__frb_api__frb_list_folder_messages_window(
    NativePortType port_,
    String store_uri,
    String credential_key,
    String folder_name,
    int start_index,
    int limit,
    String message_list_sort,
    bool use_keychain,
  ) => wasmModule.wire__crate__frb_api__frb_list_folder_messages_window(
    port_,
    store_uri,
    credential_key,
    folder_name,
    start_index,
    limit,
    message_list_sort,
    use_keychain,
  );

  void wire__crate__frb_api__frb_list_mail_folders(
    NativePortType port_,
    String store_uri,
    String credential_key,
    bool use_keychain,
  ) => wasmModule.wire__crate__frb_api__frb_list_mail_folders(
    port_,
    store_uri,
    credential_key,
    use_keychain,
  );

  void wire__crate__frb_api__frb_load_config_json(
    NativePortType port_,
    String path,
  ) => wasmModule.wire__crate__frb_api__frb_load_config_json(port_, path);

  void wire__crate__frb_api__frb_mail_body_message_url(
    NativePortType port_,
    String store_key,
    String folder_name,
    String message_id,
    String extra_query,
  ) => wasmModule.wire__crate__frb_api__frb_mail_body_message_url(
    port_,
    store_key,
    folder_name,
    message_id,
    extra_query,
  );

  void wire__crate__frb_api__frb_mail_body_register_store(
    NativePortType port_,
    String store_uri,
    String credential_key,
    bool use_keychain,
  ) => wasmModule.wire__crate__frb_api__frb_mail_body_register_store(
    port_,
    store_uri,
    credential_key,
    use_keychain,
  );

  void wire__crate__frb_api__frb_mail_body_server_init(NativePortType port_) =>
      wasmModule.wire__crate__frb_api__frb_mail_body_server_init(port_);

  void wire__crate__frb_api__frb_mail_body_set_tls_require_client_cert(
    NativePortType port_,
    bool require,
  ) => wasmModule
      .wire__crate__frb_api__frb_mail_body_set_tls_require_client_cert(
        port_,
        require,
      );

  void wire__crate__frb_api__frb_remove_account(
    NativePortType port_,
    String path,
    String account_id,
  ) => wasmModule.wire__crate__frb_api__frb_remove_account(
    port_,
    path,
    account_id,
  );

  void wire__crate__frb_api__frb_rename_mail_folder(
    NativePortType port_,
    String store_uri,
    String credential_key,
    String old_name,
    String new_name,
    bool use_keychain,
  ) => wasmModule.wire__crate__frb_api__frb_rename_mail_folder(
    port_,
    store_uri,
    credential_key,
    old_name,
    new_name,
    use_keychain,
  );

  void wire__crate__frb_api__frb_save_config_json(
    NativePortType port_,
    String path,
    String config_json,
  ) => wasmModule.wire__crate__frb_api__frb_save_config_json(
    port_,
    path,
    config_json,
  );

  void wire__crate__frb_api__frb_save_store_credential(
    NativePortType port_,
    String credential_id,
    String store_uri,
    String username,
    String password,
    bool use_keychain,
  ) => wasmModule.wire__crate__frb_api__frb_save_store_credential(
    port_,
    credential_id,
    store_uri,
    username,
    password,
    use_keychain,
  );

  void wire__crate__frb_api__frb_save_transport_credential(
    NativePortType port_,
    String transport_id,
    String username,
    String password,
    bool use_keychain,
  ) => wasmModule.wire__crate__frb_api__frb_save_transport_credential(
    port_,
    transport_id,
    username,
    password,
    use_keychain,
  );

  void wire__crate__frb_api__frb_transfer_mail_messages(
    NativePortType port_,
    String source_store_uri,
    String source_credential_key,
    String source_folder,
    String dest_store_uri,
    String dest_credential_key,
    String dest_folder,
    JSAny message_ids,
    bool is_move,
    bool use_keychain,
  ) => wasmModule.wire__crate__frb_api__frb_transfer_mail_messages(
    port_,
    source_store_uri,
    source_credential_key,
    source_folder,
    dest_store_uri,
    dest_credential_key,
    dest_folder,
    message_ids,
    is_move,
    use_keychain,
  );

  void wire__crate__frb_api__frb_upsert_account(
    NativePortType port_,
    String path,
    String account_json,
  ) => wasmModule.wire__crate__frb_api__frb_upsert_account(
    port_,
    path,
    account_json,
  );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__frb_api__frb_account_default(NativePortType port_);

  external void wire__crate__frb_api__frb_config_default(NativePortType port_);

  external void wire__crate__frb_api__frb_create_mail_folder(
    NativePortType port_,
    String store_uri,
    String credential_key,
    String folder_path,
    bool use_keychain,
  );

  external void wire__crate__frb_api__frb_delete_mail_folder(
    NativePortType port_,
    String store_uri,
    String credential_key,
    String folder_name,
    bool use_keychain,
  );

  external void wire__crate__frb_api__frb_expunge_mail_folder(
    NativePortType port_,
    String store_uri,
    String credential_key,
    String folder_name,
    bool use_keychain,
  );

  external void wire__crate__frb_api__frb_fetch_folder_message_part(
    NativePortType port_,
    String store_uri,
    String credential_key,
    String folder_name,
    String message_id,
    String imap_section,
    String transfer_encoding,
    bool use_keychain,
  );

  external void wire__crate__frb_api__frb_get_folder_message(
    NativePortType port_,
    String store_uri,
    String credential_key,
    String folder_name,
    String message_id,
    bool use_keychain,
  );

  external void wire__crate__frb_api__frb_list_folder_messages(
    NativePortType port_,
    String store_uri,
    String credential_key,
    String folder_name,
    int skip,
    int limit,
    bool use_keychain,
  );

  external void wire__crate__frb_api__frb_list_folder_messages_window(
    NativePortType port_,
    String store_uri,
    String credential_key,
    String folder_name,
    int start_index,
    int limit,
    String message_list_sort,
    bool use_keychain,
  );

  external void wire__crate__frb_api__frb_list_mail_folders(
    NativePortType port_,
    String store_uri,
    String credential_key,
    bool use_keychain,
  );

  external void wire__crate__frb_api__frb_load_config_json(
    NativePortType port_,
    String path,
  );

  external void wire__crate__frb_api__frb_mail_body_message_url(
    NativePortType port_,
    String store_key,
    String folder_name,
    String message_id,
    String extra_query,
  );

  external void wire__crate__frb_api__frb_mail_body_register_store(
    NativePortType port_,
    String store_uri,
    String credential_key,
    bool use_keychain,
  );

  external void wire__crate__frb_api__frb_mail_body_server_init(
    NativePortType port_,
  );

  external void wire__crate__frb_api__frb_mail_body_set_tls_require_client_cert(
    NativePortType port_,
    bool require,
  );

  external void wire__crate__frb_api__frb_remove_account(
    NativePortType port_,
    String path,
    String account_id,
  );

  external void wire__crate__frb_api__frb_rename_mail_folder(
    NativePortType port_,
    String store_uri,
    String credential_key,
    String old_name,
    String new_name,
    bool use_keychain,
  );

  external void wire__crate__frb_api__frb_save_config_json(
    NativePortType port_,
    String path,
    String config_json,
  );

  external void wire__crate__frb_api__frb_save_store_credential(
    NativePortType port_,
    String credential_id,
    String store_uri,
    String username,
    String password,
    bool use_keychain,
  );

  external void wire__crate__frb_api__frb_save_transport_credential(
    NativePortType port_,
    String transport_id,
    String username,
    String password,
    bool use_keychain,
  );

  external void wire__crate__frb_api__frb_transfer_mail_messages(
    NativePortType port_,
    String source_store_uri,
    String source_credential_key,
    String source_folder,
    String dest_store_uri,
    String dest_credential_key,
    String dest_folder,
    JSAny message_ids,
    bool is_move,
    bool use_keychain,
  );

  external void wire__crate__frb_api__frb_upsert_account(
    NativePortType port_,
    String path,
    String account_json,
  );
}
