// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';
import 'frb_api.dart';
import 'frb_api/frb_json.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  Map<String, List<String>> dco_decode_Map_String_list_String_None(dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountParseState dco_decode_account_parse_state(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AccountParseState dco_decode_box_autoadd_account_parse_state(dynamic raw);

  @protected
  FrbAccount dco_decode_box_autoadd_frb_account(dynamic raw);

  @protected
  FrbConfig dco_decode_box_autoadd_frb_config(dynamic raw);

  @protected
  FrbTransport dco_decode_box_autoadd_frb_transport(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  CfgStack dco_decode_cfg_stack(dynamic raw);

  @protected
  FrbAccount dco_decode_frb_account(dynamic raw);

  @protected
  FrbConfig dco_decode_frb_config(dynamic raw);

  @protected
  FrbConfigParse dco_decode_frb_config_parse(dynamic raw);

  @protected
  FrbTransport dco_decode_frb_transport(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CfgStack> dco_decode_list_cfg_stack(dynamic raw);

  @protected
  List<FrbAccount> dco_decode_list_frb_account(dynamic raw);

  @protected
  List<FrbTransport> dco_decode_list_frb_transport(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, List<String>)> dco_decode_list_record_string_list_string(
    dynamic raw,
  );

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  (String, List<String>) dco_decode_record_string_list_string(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, List<String>> sse_decode_Map_String_list_String_None(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountParseState sse_decode_account_parse_state(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AccountParseState sse_decode_box_autoadd_account_parse_state(
    SseDeserializer deserializer,
  );

  @protected
  FrbAccount sse_decode_box_autoadd_frb_account(SseDeserializer deserializer);

  @protected
  FrbConfig sse_decode_box_autoadd_frb_config(SseDeserializer deserializer);

  @protected
  FrbTransport sse_decode_box_autoadd_frb_transport(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  CfgStack sse_decode_cfg_stack(SseDeserializer deserializer);

  @protected
  FrbAccount sse_decode_frb_account(SseDeserializer deserializer);

  @protected
  FrbConfig sse_decode_frb_config(SseDeserializer deserializer);

  @protected
  FrbConfigParse sse_decode_frb_config_parse(SseDeserializer deserializer);

  @protected
  FrbTransport sse_decode_frb_transport(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CfgStack> sse_decode_list_cfg_stack(SseDeserializer deserializer);

  @protected
  List<FrbAccount> sse_decode_list_frb_account(SseDeserializer deserializer);

  @protected
  List<FrbTransport> sse_decode_list_frb_transport(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, List<String>)> sse_decode_list_record_string_list_string(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  (String, List<String>) sse_decode_record_string_list_string(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_list_String_None(
    Map<String, List<String>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_parse_state(
    AccountParseState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_account_parse_state(
    AccountParseState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_account(
    FrbAccount self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_config(
    FrbConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_transport(
    FrbTransport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cfg_stack(CfgStack self, SseSerializer serializer);

  @protected
  void sse_encode_frb_account(FrbAccount self, SseSerializer serializer);

  @protected
  void sse_encode_frb_config(FrbConfig self, SseSerializer serializer);

  @protected
  void sse_encode_frb_config_parse(
    FrbConfigParse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_transport(FrbTransport self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cfg_stack(List<CfgStack> self, SseSerializer serializer);

  @protected
  void sse_encode_list_frb_account(
    List<FrbAccount> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_transport(
    List<FrbTransport> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_list_string(
    List<(String, List<String>)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_list_string(
    (String, List<String>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
