// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_api.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `addresses_from_from_field`, `append_to_mail_folder`, `apply_mail_crypto_for_send`, `batch_mail_op_result_from_transfer`, `blocking_get_message_raw`, `conversation_to_message_summary`, `create_mail_folder`, `delete_mail_folder`, `delete_mail_messages_result`, `detail_from_display`, `detail_from_env_and_body`, `dsn_setting_to_notify_param`, `expunge_mail_folder`, `fetch_folder_message_part_json`, `folder_range_for_indices`, `for_each_row`, `format_address_list_maybe_nostr`, `format_address_maybe_nostr`, `format_address`, `format_bytes_base64`, `format_list_folder_messages_window_response`, `format_message_detail`, `format_message_summary_array`, `format_transfer_mail_messages_response`, `frb_runtime_handle`, `generate_smtp_compose_message_id_impl`, `get_folder_message_detail`, `get_folder_message_json_full_raw`, `get_folder_message_json`, `imap_mirror_sent_after_smtp_enabled`, `list_folder_messages_json`, `list_folder_messages_summaries`, `list_folder_messages_window_json`, `list_folder_messages_window_response`, `list_strategy`, `load_credential_entry`, `load_folder_message_detail_json`, `mark_folder_message_read`, `merge_nostr_relay_lists`, `message_detail_json_to_frb`, `nostr_publish_profile_metadata`, `nostr_relay_sets_differ`, `nostr_relay_url_key`, `nostr_sync_remote_profile_and_relays`, `rename_mail_folder`, `row_count`, `save_imap_draft_json`, `send_gmail_json`, `send_nntp_json`, `send_smtp_json`, `smtp_credential_required_message`, `smtp_parse_addrs`, `smtp_resolve_auth_from_ehlo`, `smtp_tls_mode`, `start_index`, `subscription_available_array_json`, `to_frb_message_summary`, `to_message_list_row_summary`, `total`, `transfer_mail_messages_result`, `u64_json`, `verify_smtp_transport`, `wait_folder_append`, `wait_folder_copy_one`, `wait_folder_delete`, `wait_folder_move_one`, `wait_message_count`, `write_attachment_detail`, `write_message_summary`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AttachmentDetailJson`, `ListFolderMessagesWindowResponse`, `MessageDetailJson`, `MessageSummaryJson`, `TransferMailMessagesResponse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<ListFolderMessagesResult> listFolderMessagesResult({
  required FrbAccount acc,
  required String folderName,
  required BigInt skip,
  required BigInt limit,
  required bool useKeychain,
}) => RustLib.instance.api.crateFrbApiFrbMailListFolderMessagesResult(
  acc: acc,
  folderName: folderName,
  skip: skip,
  limit: limit,
  useKeychain: useKeychain,
);

Future<ListFolderMessagesWindowResult> listFolderMessagesWindowResult({
  required FrbAccount acc,
  required String folderName,
  required BigInt startIndex,
  required BigInt limit,
  required String messageListSort,
  required bool useKeychain,
}) => RustLib.instance.api.crateFrbApiFrbMailListFolderMessagesWindowResult(
  acc: acc,
  folderName: folderName,
  startIndex: startIndex,
  limit: limit,
  messageListSort: messageListSort,
  useKeychain: useKeychain,
);

class FrbBatchMailOperationResult {
  final List<FrbMailOperationItem> results;
  final BigInt okCount;
  final BigInt failedCount;

  const FrbBatchMailOperationResult({
    required this.results,
    required this.okCount,
    required this.failedCount,
  });

  @override
  int get hashCode =>
      results.hashCode ^ okCount.hashCode ^ failedCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbBatchMailOperationResult &&
          runtimeType == other.runtimeType &&
          results == other.results &&
          okCount == other.okCount &&
          failedCount == other.failedCount;
}

class FrbComposeAttachment {
  final String? filename;
  final String mimeType;
  final String bytesBase64;

  const FrbComposeAttachment({
    this.filename,
    required this.mimeType,
    required this.bytesBase64,
  });

  @override
  int get hashCode =>
      filename.hashCode ^ mimeType.hashCode ^ bytesBase64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbComposeAttachment &&
          runtimeType == other.runtimeType &&
          filename == other.filename &&
          mimeType == other.mimeType &&
          bytesBase64 == other.bytesBase64;
}

/// Outgoing SMTP / Gmail REST / IMAP draft save (camelCase in Dart).
class FrbComposeMessage {
  final String from;
  final List<String> to;
  final List<String> cc;
  final List<String> bcc;
  final String subject;
  final String bodyPlain;
  final String? bodyHtml;
  final List<FrbComposeAttachment> attachments;
  final String? dsnNotify;
  final String? storeAccountId;
  final String? inReplyTo;
  final String? references;
  final String? messageId;

  /// `none` | `sign` | `encrypt` | `sign_encrypt` (camelCase `cryptoMode` in JSON); legacy
  /// `smime_sign` / `pgp_sign` / `*_sign_encrypt` are accepted and normalized.
  final String? cryptoMode;

  const FrbComposeMessage({
    required this.from,
    required this.to,
    required this.cc,
    required this.bcc,
    required this.subject,
    required this.bodyPlain,
    this.bodyHtml,
    required this.attachments,
    this.dsnNotify,
    this.storeAccountId,
    this.inReplyTo,
    this.references,
    this.messageId,
    this.cryptoMode,
  });

  @override
  int get hashCode =>
      from.hashCode ^
      to.hashCode ^
      cc.hashCode ^
      bcc.hashCode ^
      subject.hashCode ^
      bodyPlain.hashCode ^
      bodyHtml.hashCode ^
      attachments.hashCode ^
      dsnNotify.hashCode ^
      storeAccountId.hashCode ^
      inReplyTo.hashCode ^
      references.hashCode ^
      messageId.hashCode ^
      cryptoMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbComposeMessage &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          to == other.to &&
          cc == other.cc &&
          bcc == other.bcc &&
          subject == other.subject &&
          bodyPlain == other.bodyPlain &&
          bodyHtml == other.bodyHtml &&
          attachments == other.attachments &&
          dsnNotify == other.dsnNotify &&
          storeAccountId == other.storeAccountId &&
          inReplyTo == other.inReplyTo &&
          references == other.references &&
          messageId == other.messageId &&
          cryptoMode == other.cryptoMode;
}

class FrbFetchedMessagePart {
  final String bytesBase64;

  const FrbFetchedMessagePart({required this.bytesBase64});

  @override
  int get hashCode => bytesBase64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbFetchedMessagePart &&
          runtimeType == other.runtimeType &&
          bytesBase64 == other.bytesBase64;
}

class FrbFolderMessageDetail {
  final String subject;
  final String from;
  final String to;
  final String? cc;
  final PlatformInt64? dateMs;
  final String? messageId;
  final String? references;
  final String? bodyPlain;
  final String? bodyHtml;
  final List<FrbMessageAttachmentDetail> attachments;

  /// Matrix Megolm: decryption failed; UI should show recovery steps instead of body text.
  final bool? matrixE2EeUndecryptable;

  /// Inbound PGP/S/MIME signature check vs contacts (`valid` / `invalid` / `unknown`).
  final String? signatureVerification;

  const FrbFolderMessageDetail({
    required this.subject,
    required this.from,
    required this.to,
    this.cc,
    this.dateMs,
    this.messageId,
    this.references,
    this.bodyPlain,
    this.bodyHtml,
    required this.attachments,
    this.matrixE2EeUndecryptable,
    this.signatureVerification,
  });

  @override
  int get hashCode =>
      subject.hashCode ^
      from.hashCode ^
      to.hashCode ^
      cc.hashCode ^
      dateMs.hashCode ^
      messageId.hashCode ^
      references.hashCode ^
      bodyPlain.hashCode ^
      bodyHtml.hashCode ^
      attachments.hashCode ^
      matrixE2EeUndecryptable.hashCode ^
      signatureVerification.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbFolderMessageDetail &&
          runtimeType == other.runtimeType &&
          subject == other.subject &&
          from == other.from &&
          to == other.to &&
          cc == other.cc &&
          dateMs == other.dateMs &&
          messageId == other.messageId &&
          references == other.references &&
          bodyPlain == other.bodyPlain &&
          bodyHtml == other.bodyHtml &&
          attachments == other.attachments &&
          matrixE2EeUndecryptable == other.matrixE2EeUndecryptable &&
          signatureVerification == other.signatureVerification;
}

class FrbMailOperationItem {
  final String id;
  final bool ok;
  final String? error;

  const FrbMailOperationItem({required this.id, required this.ok, this.error});

  @override
  int get hashCode => id.hashCode ^ ok.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbMailOperationItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          ok == other.ok &&
          error == other.error;
}

class FrbMailSubscriptionAvailableRow {
  final String id;
  final bool isSubscribed;
  final String? displayName;
  final BigInt? unread;
  final bool allowUnsubscribe;

  const FrbMailSubscriptionAvailableRow({
    required this.id,
    required this.isSubscribed,
    this.displayName,
    this.unread,
    required this.allowUnsubscribe,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      isSubscribed.hashCode ^
      displayName.hashCode ^
      unread.hashCode ^
      allowUnsubscribe.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbMailSubscriptionAvailableRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          isSubscribed == other.isSubscribed &&
          displayName == other.displayName &&
          unread == other.unread &&
          allowUnsubscribe == other.allowUnsubscribe;
}

class FrbMessageAttachmentDetail {
  final String? filename;
  final String contentType;
  final BigInt sizeBytes;
  final String transferEncoding;
  final String? imapSection;
  final String? contentId;
  final String? dataBase64;

  const FrbMessageAttachmentDetail({
    this.filename,
    required this.contentType,
    required this.sizeBytes,
    required this.transferEncoding,
    this.imapSection,
    this.contentId,
    this.dataBase64,
  });

  @override
  int get hashCode =>
      filename.hashCode ^
      contentType.hashCode ^
      sizeBytes.hashCode ^
      transferEncoding.hashCode ^
      imapSection.hashCode ^
      contentId.hashCode ^
      dataBase64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbMessageAttachmentDetail &&
          runtimeType == other.runtimeType &&
          filename == other.filename &&
          contentType == other.contentType &&
          sizeBytes == other.sizeBytes &&
          transferEncoding == other.transferEncoding &&
          imapSection == other.imapSection &&
          contentId == other.contentId &&
          dataBase64 == other.dataBase64;
}

/// Message row summary for list APIs (same data as [MessageSummaryJson]).
class FrbMessageSummary {
  final String id;
  final String from;
  final String subject;
  final PlatformInt64? dateMs;
  final bool isRead;
  final bool markedForDeletion;
  final String? nostrSenderPubkeyHex;

  const FrbMessageSummary({
    required this.id,
    required this.from,
    required this.subject,
    this.dateMs,
    required this.isRead,
    required this.markedForDeletion,
    this.nostrSenderPubkeyHex,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      from.hashCode ^
      subject.hashCode ^
      dateMs.hashCode ^
      isRead.hashCode ^
      markedForDeletion.hashCode ^
      nostrSenderPubkeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbMessageSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          from == other.from &&
          subject == other.subject &&
          dateMs == other.dateMs &&
          isRead == other.isRead &&
          markedForDeletion == other.markedForDeletion &&
          nostrSenderPubkeyHex == other.nostrSenderPubkeyHex;
}

/// NNTP post payload (camelCase in Dart).
class FrbNntpComposeMessage {
  final String from;
  final List<String> newsgroups;
  final String subject;
  final String bodyPlain;
  final List<FrbComposeAttachment> attachments;
  final String? inReplyTo;
  final String? references;

  const FrbNntpComposeMessage({
    required this.from,
    required this.newsgroups,
    required this.subject,
    required this.bodyPlain,
    required this.attachments,
    this.inReplyTo,
    this.references,
  });

  @override
  int get hashCode =>
      from.hashCode ^
      newsgroups.hashCode ^
      subject.hashCode ^
      bodyPlain.hashCode ^
      attachments.hashCode ^
      inReplyTo.hashCode ^
      references.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbNntpComposeMessage &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          newsgroups == other.newsgroups &&
          subject == other.subject &&
          bodyPlain == other.bodyPlain &&
          attachments == other.attachments &&
          inReplyTo == other.inReplyTo &&
          references == other.references;
}

/// Result of [list_folder_messages_json] / [list_folder_messages_result]: newest-first page.
class ListFolderMessagesResult {
  final List<FrbMessageSummary> messages;

  const ListFolderMessagesResult({required this.messages});

  @override
  int get hashCode => messages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListFolderMessagesResult &&
          runtimeType == other.runtimeType &&
          messages == other.messages;
}

class ListFolderMessagesWindowResult {
  final BigInt total;
  final BigInt startIndex;
  final String listStrategy;
  final List<FrbMessageSummary> messages;

  const ListFolderMessagesWindowResult({
    required this.total,
    required this.startIndex,
    required this.listStrategy,
    required this.messages,
  });

  @override
  int get hashCode =>
      total.hashCode ^
      startIndex.hashCode ^
      listStrategy.hashCode ^
      messages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListFolderMessagesWindowResult &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          startIndex == other.startIndex &&
          listStrategy == other.listStrategy &&
          messages == other.messages;
}
