// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `contact_row_to_json`, `normalize_email`, `now_ms`, `with_db`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ContactUpsertJson`, `EmailJson`, `GroupUpsertJson`, `PlatformContactJson`, `RepositoryUpsertJson`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Search contacts for autocomplete (display name + email).
Future<String> frbContactsSearch({
  required String query,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateFrbApiFrbContactsFrbContactsSearch(
  query: query,
  limit: limit,
);

Future<String> frbContactsGet({required PlatformInt64 contactId}) => RustLib
    .instance
    .api
    .crateFrbApiFrbContactsFrbContactsGet(contactId: contactId);

/// Lookup first contact matching email (normalized).
Future<String> frbContactsLookupByEmail({required String email}) => RustLib
    .instance
    .api
    .crateFrbApiFrbContactsFrbContactsLookupByEmail(email: email);

Future<String> frbContactsUpsert({required String contactJson}) => RustLib
    .instance
    .api
    .crateFrbApiFrbContactsFrbContactsUpsert(contactJson: contactJson);

Future<void> frbContactsDelete({required PlatformInt64 contactId}) => RustLib
    .instance
    .api
    .crateFrbApiFrbContactsFrbContactsDelete(contactId: contactId);

Future<void> frbContactsValidateExternalSharing({
  required PlatformInt64 contactId,
  required bool ok,
}) => RustLib.instance.api
    .crateFrbApiFrbContactsFrbContactsValidateExternalSharing(
      contactId: contactId,
      ok: ok,
    );

Future<String> frbContactsLearnFromMail({
  required String displayName,
  required String email,
}) => RustLib.instance.api.crateFrbApiFrbContactsFrbContactsLearnFromMail(
  displayName: displayName,
  email: email,
);

Future<String> frbContactsRepositoriesList() =>
    RustLib.instance.api.crateFrbApiFrbContactsFrbContactsRepositoriesList();

Future<String> frbContactsRepositoryUpsert({required String json}) => RustLib
    .instance
    .api
    .crateFrbApiFrbContactsFrbContactsRepositoryUpsert(json: json);

Future<void> frbContactsRepositoryDelete({
  required PlatformInt64 repositoryId,
}) => RustLib.instance.api.crateFrbApiFrbContactsFrbContactsRepositoryDelete(
  repositoryId: repositoryId,
);

Future<void> frbContactsSetRepositoryMembership({
  required PlatformInt64 contactId,
  required PlatformInt64 repositoryId,
  required bool include,
}) => RustLib.instance.api
    .crateFrbApiFrbContactsFrbContactsSetRepositoryMembership(
      contactId: contactId,
      repositoryId: repositoryId,
      include: include,
    );

Future<String> frbContactsGroupsList() =>
    RustLib.instance.api.crateFrbApiFrbContactsFrbContactsGroupsList();

Future<String> frbContactsGroupUpsert({required String json}) => RustLib
    .instance
    .api
    .crateFrbApiFrbContactsFrbContactsGroupUpsert(json: json);

Future<void> frbContactsGroupDelete({required PlatformInt64 groupId}) => RustLib
    .instance
    .api
    .crateFrbApiFrbContactsFrbContactsGroupDelete(groupId: groupId);

Future<void> frbContactsGroupAddMember({
  required PlatformInt64 contactId,
  required PlatformInt64 groupId,
}) => RustLib.instance.api.crateFrbApiFrbContactsFrbContactsGroupAddMember(
  contactId: contactId,
  groupId: groupId,
);

Future<void> frbContactsGroupRemoveMember({
  required PlatformInt64 contactId,
  required PlatformInt64 groupId,
}) => RustLib.instance.api.crateFrbApiFrbContactsFrbContactsGroupRemoveMember(
  contactId: contactId,
  groupId: groupId,
);

Future<void> frbContactsSetGroupRepositoryRule({
  required PlatformInt64 groupId,
  required PlatformInt64 repositoryId,
  required bool enable,
}) => RustLib.instance.api
    .crateFrbApiFrbContactsFrbContactsSetGroupRepositoryRule(
      groupId: groupId,
      repositoryId: repositoryId,
      enable: enable,
    );

Future<String> frbContactsApplyGroupRepositoryRules() => RustLib.instance.api
    .crateFrbApiFrbContactsFrbContactsApplyGroupRepositoryRules();

/// Compact contact rows for settings UI (picker / list).
Future<String> frbContactsListCompact({required PlatformInt64 limit}) => RustLib
    .instance
    .api
    .crateFrbApiFrbContactsFrbContactsListCompact(limit: limit);

/// All repositories with link + dirty state for one contact.
Future<String> frbContactsRepositoryLinksForContact({
  required PlatformInt64 contactId,
}) => RustLib.instance.api
    .crateFrbApiFrbContactsFrbContactsRepositoryLinksForContact(
      contactId: contactId,
    );

Future<String> frbContactsGroupRepositoryTargetsList() => RustLib.instance.api
    .crateFrbApiFrbContactsFrbContactsGroupRepositoryTargetsList();

Future<String> frbContactsGroupMembersList({required PlatformInt64 groupId}) =>
    RustLib.instance.api.crateFrbApiFrbContactsFrbContactsGroupMembersList(
      groupId: groupId,
    );

Future<void> frbContactsBulkSetRepositoryMembership({
  required String contactIdsJson,
  required PlatformInt64 repositoryId,
  required bool include,
}) => RustLib.instance.api
    .crateFrbApiFrbContactsFrbContactsBulkSetRepositoryMembership(
      contactIdsJson: contactIdsJson,
      repositoryId: repositoryId,
      include: include,
    );

/// CardDAV pull using HTTP Basic auth (credentials are not persisted by this call).
Future<String> frbContactsCarddavPull({
  required PlatformInt64 repositoryId,
  required String username,
  required String password,
}) => RustLib.instance.api.crateFrbApiFrbContactsFrbContactsCarddavPull(
  repositoryId: repositoryId,
  username: username,
  password: password,
);

/// Push dirty contacts to CardDAV (PUT vCard). Rows need `remote_href` (set after a successful pull).
Future<String> frbContactsCarddavPush({
  required PlatformInt64 repositoryId,
  required String username,
  required String password,
}) => RustLib.instance.api.crateFrbApiFrbContactsFrbContactsCarddavPush(
  repositoryId: repositoryId,
  username: username,
  password: password,
);

Future<String> frbContactsImportVcardBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateFrbApiFrbContactsFrbContactsImportVcardBytes(
      bytes: bytes,
    );

Future<String> frbContactsExportVcard({required String contactIdsJson}) =>
    RustLib.instance.api.crateFrbApiFrbContactsFrbContactsExportVcard(
      contactIdsJson: contactIdsJson,
    );

/// Walk MIME parts and concatenate embedded vCard bodies.
Future<String> frbContactsExtractVcardsFromRawMessage({
  required List<int> raw,
}) => RustLib.instance.api
    .crateFrbApiFrbContactsFrbContactsExtractVcardsFromRawMessage(raw: raw);

Future<String> frbContactsImportVcardsFromRawMessage({
  required List<int> raw,
}) => RustLib.instance.api
    .crateFrbApiFrbContactsFrbContactsImportVcardsFromRawMessage(raw: raw);

/// Merge contacts from platform address book JSON (from Flutter).
/// Payload may be a JSON array (legacy) or `{"items":[...], "repositoryId": optional id}` to link new rows to a repository.
Future<String> frbContactsMergePlatformJson({required String payload}) =>
    RustLib.instance.api.crateFrbApiFrbContactsFrbContactsMergePlatformJson(
      payload: payload,
    );

Future<String> frbContactsSyncRepository({
  required PlatformInt64 repositoryId,
}) => RustLib.instance.api.crateFrbApiFrbContactsFrbContactsSyncRepository(
  repositoryId: repositoryId,
);

Future<String> frbContactsSyncStatus() =>
    RustLib.instance.api.crateFrbApiFrbContactsFrbContactsSyncStatus();
